### ISSUE TITLE
Instruments query limit

### ISSUE THREAD

**Issue by JGomez110** [robinhood-unofficial/Robinhood#101]
It seems to me like there is an limit to the amount of instruments returned. Tried to get the instrument of 'SH' and I got this for a return. 
`for stock in account.instruments('SH'):
    print stock['symbol']`
SHOP
SHW
SHPG
SHV
SHY
SHAK
SHO
SHOO
SHM
SHYG

Tried again with a more generic symbol which should have over 10 results:
`for stock in account.instruments('S'):
    print stock['symbol']`
SPY
S
SNAP
SPGI
SPOT
SQ
SLB
SBUX
SCHW
SHOP

**Comment by jasonleehodges** [comment]
Seems like a limitation of the instruments endpoint. Looks like there might be a better search endpoint that Robinhood web is using but it returns several categories of results:

`https://api.robinhood.com/midlands/search/?query=s`

We should perhaps think about adding in an enhancement if this is desired functionality.
