### ISSUE TITLE
how to find symbols for owned securities

### ISSUE THREAD

**Issue by grahamseamans** [robinhood-unofficial/Robinhood#104]
Hello!

Is there a way to find the symbol of an owned security? I see that there is a url in the dict returned from securities_owned(), but I don't see how to get the symbol.

Is there a way to do this?

Thank you,
G

**Comment by jasonleehodges** [comment]
You just have to call a get request on that URL and it will return a JSON object that has a "symbol" key. Or you could parse out the instrument id from that URL and use that to call the instrument method.

**Comment by jasonleehodges** [comment]
```
from Robinhood import Robinhood

rb = Robinhood()
owned = rb.securities_owned()
url = owned["results"][0]["instrument"]
sample_instrument = rb.get_url(url)
symbol = sample_instrument["symbol"]
```

Where 0 is the first security in the list of owned securities. Does that help?

**Comment by jasonleehodges** [comment]
@grahamseamans Were you able to figure this out?

**Comment by jmercadodev** [comment]
This worked for me! Thanks : )
