### ISSUE TITLE
Problem with Cancel Order

### ISSUE THREAD

**Issue by aamazie** [robinhood-unofficial/Robinhood#107]
I am trying to figure out how to cancel all the open orders.. I know the function that did that was gotten rid of for some reason. Instead I am trying to just delete one order at a time with the cancel_order and loop through. However, when I put in a valid "id" string from the order dictionary it tells me it's not a valid order_id string, so I can't iterate over the orders myself. I take the "id" from the order history. I assume that's what the order_id is. If that's correct, then it's throwing the "not a valid order_id string" error when something else is going wrong. Help would be appreciated.

**Comment by jasonleehodges** [comment]
You're iterating over all orders in your order history and trying to cancel them? Are you sure the orders you are trying to cancel are in fact open?

**Comment by aamazie** [comment]
The issue is that I can't cancel any orders. The cancel_order doesn't work.

**Comment by aamazie** [comment]
So if I do something like this:

orderid = my_trader.order_history()["results"][0]["id"]
my_trader.cancel_order(orderid)

I get this:
ValueError: Cancelling orders requires a valid order_id string

**Comment by jasonleehodges** [comment]
Well my point is, if you are passing in an order that is not open then you can't cancel it. You might want to ensure that your orders are open before you try to cancel:

```open_orders = [order for order in orders['history'] if order['cancel']]```

Looking at the code though for the `cancel_order()` method it looks like that particular ValueError is only raise if you don't pass the order id in as a str, which means you are probably trying to pass it in as an integer. Try this:

```
orderid = my_trader.order_history()["results"][0]["id"]
my_trader.cancel_order(str(ordered))
```

**Comment by jasonleehodges** [comment]
Yeah, let me know if it's just a string issue. Because if it is, I think that method needs to be enhanced to just coerce the argument to a string rather than kicking it out to a ValueError.

**Comment by aamazie** [comment]
I tried the things you suggested to be sure and it still throws the same error...

**Comment by jasonleehodges** [comment]
I just looked at the code block again. Looks like it's checking if it _is_ a string rather than if it _is not_ a string. If it is a string then it throws the error. Maybe try `my_trader.cancel_order(int(orderid))`

**Comment by aamazie** [comment]
First of all, that would make no sense.. It would have to be a string, not an integer. It has dashes and letters. I get ValueError: invalid literal for int() with base 10.
Second.. I don't see the code doing that. It says If the order_id is a string, try to post the cancel.. but then there's an Else statement right after the first If statement, which I believe would block the If and Else statements below it.. I had also tried having the entire order dictionary go through and it gave me the same error about the invalid string, so there's an issue there too.

**Comment by aamazie** [comment]
It should be something like
If order is string, try to post the cancel, except exception.
If order is a dictionary and order.get('cancel') is not None, try to post cancel, except exception.
Elif order is not a dictionary or string, throw error about it not being a compatible order_id string or open order dictionary.

**Comment by jasonleehodges** [comment]
Oh yeah good point, I was right the first time on that if condition. Need the coffee to kick in still. Definitely seems a bug here to me. Can you try commenting out the first if/else and just keep the try/except to see if it will actually attempt to post the cancel?

**Comment by aamazie** [comment]
How do I do that? I'm using the module from the Git clone.

Also, I would suggest actual code for rewriting but I'm not an expert in making APIs.

If you need to get back to me later on this, that's fine.

**Comment by aamazie** [comment]
If you want to invite me as a collaborator I'd do my best to rewrite the cancel_order.

**Comment by aamazie** [comment]
Ok, I think I figured out the problem and I've rewritten the code so that it should work now.

In the first If statement, you aren't actually posting the cancel request, you're only doing a get request. Then you hit the Else statement that throws the Value Error. THEN, you do an If statement to see if the order is open and only then do you post the cancel request, which it never gets to because it would have hit the Value Error from the Else statement above.

I haven't collaborated on GitHub before, and I would appreciate it for my resume, so if you invite me to be a Collaborator on this and direct me to where to edit the code, I'll paste in my replacement and test it.

**Comment by jasonleehodges** [comment]
The best thing to do is fork the code, create your own branch, update the code on your branch, and then submit a pull request. From there @Jamonek can review and approve if the code works.

**Comment by aamazie** [comment]
Alright, thank you. I sent it over.
