### ISSUE TITLE
Place Limit Order

### ISSUE THREAD

**Issue by empireofryan** [robinhood-unofficial/Robinhood#112]
Any idea how to place a limit order rather than a market buy (which is essentially a limit of 5% over the current stock price)?

Only method I see in place is: place_buy_order

Is there a place_limit_order and if so what are the arguments?

**Comment by jasonleehodges** [comment]
Checkout the method signature for `place_order()`. One of the arguments is "order" and it is set to "market" by default but can be set to "limit".

**Comment by badubies** [comment]
You could also call this:

     place_limit_buy_order(instrument_URL=None, symbol=None, time_in_force=None, price=None, quantity=None):

            Notes:
                If only one of the instrument_URL or symbol are passed as
                arguments the other will be looked up automatically.
            Args:
                instrument_URL (str): The RH URL of the instrument
                symbol (str): The ticker symbol of the instrument
                time_in_force (str): 'GFD' or 'GTC' (day or until cancelled)
                price (float): The max price you're willing to pay per share
                quantity (int): Number of shares to buy

**Comment by manfredbastero** [comment]
I tried the following 
buy_order = my_trader.place_limit_buy_order(instrument_URL=None, symbol="UVXY", time_in_force=None, price=2, quantity=5)

and got the following error

Traceback (most recent call last):
  File "C:\Users\Home\Documents\New folder\robinhoodtrader.py", line 36, in <module>
    buy_order = my_trader.place_limit_buy_order(instrument_URL=None, symbol="UVXY", time_in_force=None, price=2, quantity=5)
  File "C:\Program Files\Python36\lib\site-packages\Robinhood\Robinhood.py", line 1021, in place_limit_buy_order
    quantity=quantity))
  File "C:\Program Files\Python36\lib\site-packages\Robinhood\Robinhood.py", line 1334, in submit_order
    res.raise_for_status()
  File "C:\Program Files\Python36\lib\site-packages\requests\models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.robinhood.com/orders/

please help

**Comment by badubies** [comment]
You must specify time_in_force. 'GTC' (Good till Cancelled) if you want to keep your order open longer than a day, or 'GFD' (Good for day).
