### ISSUE TITLE
Execution report

### ISSUE THREAD

**Issue by pablomedrano10** [robinhood-unofficial/Robinhood#114]
Does Robinhood provide some kind of order execution report or status?
Can anyone share an example as my account is under review process.
Thanks

**Comment by westonplatter** [comment]
Short answer, no. You don't get trade confirmations at the end of the trading day. 

But, you can export order history at any time. See this example from a library I built, simple_metrics (https://github.com/westonplatter/simple_metrics), 

```
from simple_metrics import fetch, export
import configparser

config = configparser.ConfigParser()
config.read('config.debug.ini')


account = {
        'username': config['account']['username'],
        'password': config['account']['password']}


fetch_options = {}
stock_orders = fetch.stock_orders(account, fetch_options)
print("Fetched {} stock trades".format(len(stock_orders)))


export_options = {}
export.stock_orders(stock_orders, export_options)
print("Finished writing stock_orders to stock_orders.csv")
```

@pablomedrano10 does that answer your question.

**Comment by pablomedrano10** [comment]
@westonplatter that the alternative I had in mind. Either check order history or own stocks. It possible but it is a worse solution in my opinion.

**Comment by westonplatter** [comment]
@pablomedrano10 what's the value of getting an order execution report?

**Comment by pablomedrano10** [comment]
@westonplatter it is to know if you order has been filled and at what price each stock
