### ISSUE TITLE
How to access historical data?

### ISSUE THREAD

**Issue by mhaytmyr** [robinhood-unofficial/Robinhood#119]
I am trying to access historical data using get_historical_quotes(). I am not sure how to use "span" argument in this method. Documentation is not helpful here, could you provide simple example?

**Comment by francisbitontistudio** [comment]
Yes, can someone answer this?

**Comment by tobyatgithub** [comment]
Hope some help/example on that! 
From document of "get_historical_quotes", it seems that we can set interval = ‘week'.
I tried '100', '150', '200' on span but non of them worked. What's the write format for span?

**Comment by d5lewis** [comment]
Also worked for me:
interval="5minute", span = "day"
