### ISSUE TITLE
Error executing order (Stop loss)

### ISSUE THREAD

**Issue by Racerx250** [robinhood-unofficial/Robinhood#132]
Hi Jamonek,

I just want to first say thank you a ton for making an easy to use and public API. It's worked great for me so far and I've had a lot of success in my algo thanks to you! Ok, on the main topic, I just started implementing a new method which involves stop loss, and it seems that regardless of the order that I put in, it always gives me back "Error executing order." I was just wondering if this was something on my end or a current bug in the code.

Thanks in advance!

**Comment by jasonleehodges** [comment]
@Racerx250 What method are you calling?
