### ISSUE TITLE
Login endpoint gives 404

### ISSUE THREAD

**Issue by justin-pierce** [robinhood-unofficial/Robinhood#135]
Robinhood seems to have removed the login endpoint -- https://api.robinhood.com/api-token-auth/ now returns 404 not found. Anybody have a workaround? 

edit: see here for workaround: https://github.com/Jamonek/Robinhood/issues/135#issuecomment-420699999

**Comment by batcavenet** [comment]
not yet.. opened a support ticket to ask but I don't expect an answer there necessarily

**Comment by justin-pierce** [comment]
Here's a way to get an 'access_token' from username/pwd: https://github.com/westonplatter/fast_arrow/issues/13#issuecomment-414080185

But that seems to be different than the 'token' we used to get? Robinhood class has auth_token and oauth_token -- I assume the above returns oath)token, not sure how to get auth_token.

**Comment by batcavenet** [comment]
someone gave this info- seems interesting

https://github.com/sanko/Robinhood/issues/87

**Comment by justin-pierce** [comment]
Ok I think I got it working. Basically you use what I linked to here: 

> Here's a way to get an 'access_token' from username/pwd: [westonplatter/fast_arrow#13 (comment)](https://github.com/westonplatter/fast_arrow/issues/13#issuecomment-414080185)
> 
> But that seems to be different than the 'token' we used to get? Robinhood class has auth_token and oauth_token -- I assume the above returns oath_token, not sure how to get auth_token.

Then when you set token in authorization header, change from 

`self.headers['Authorization'] = 'Token ' + self.auth_token`

to 

`self.headers['Authorization'] = 'Bearer ' + self.oauth_token`

(make sure you set oath_token from 'access_token' first)

**Comment by batcavenet** [comment]
Great info- what file do you change this in for this library?

**Comment by batcavenet** [comment]
Thanks Justin-pierce

**Comment by morgenfriedel** [comment]
When I add your changes, I get a 405 error:

`Traceback (most recent call last):
  File "/var/www/robinhood/Robinhood/Robinhood.py", line 119, in login
    res.raise_for_status()
  File "/home/user/.local/lib/python3.5/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 405 Client Error: Method Not Allowed for url: https://api.robinhood.com/oauth2/token/
`

**Comment by desicruizer** [comment]
> Ok I think I got it working. Basically you use what I linked to here:
> 
> > Here's a way to get an 'access_token' from username/pwd: [westonplatter/fast_arrow#13 (comment)](https://github.com/westonplatter/fast_arrow/issues/13#issuecomment-414080185)
> > But that seems to be different than the 'token' we used to get? Robinhood class has auth_token and oauth_token -- I assume the above returns oath_token, not sure how to get auth_token.
> 
> Then when you set token in authorization header, change from
> 
> `self.headers['Authorization'] = 'Token ' + self.auth_token`
> 
> to
> 
> `self.headers['Authorization'] = 'Bearer ' + self.oauth_token`
> 
> (make sure you set oath_token from 'access_token' first)
> 
> edit: my new login call is
> 
> ` def login(self,
> username,
> password,
> mfa_code=None):
> """Save and test login info for Robinhood accounts
> 
> ```
>     Args:
>         username (str): username
>         password (str): password
> 
>     Returns:
>         (bool): received valid auth token
> 
>     """
> 
>     self.username = username
>     self.password = password
>     payload = {
>         'client_id': 'c82SH0WZOsabOXGP2sxqcj34FxkvfnWRZBKlBjFS',
>         'expires_in': 86400,
>         'grant_type': 'password',
>         'password': self.password,
>         'scope': 'internal',
>         'username': self.username
>     }
> 
>     if mfa_code:
>         payload['mfa_code'] = mfa_code
> 
>     try:
>         res = self.session.post('https://api.robinhood.com/oauth2/token/', data=payload, timeout=15)
>         res.raise_for_status()
>         data = res.json()
>         print(data)
>     except requests.exceptions.HTTPError:
>         raise RH_exception.LoginFailed()
> 
>     if 'mfa_required' in data.keys():           # pragma: no cover
>         raise RH_exception.TwoFactorRequired()  # requires a second call to enable 2FA
> 
>     if 'access_token' in data.keys():
>         self.oauth_token = data['access_token']
>         self.headers['Authorization'] = 'Bearer ' + self.oauth_token
>         return True
> 
>     return False`
> ```
> Not sure if this token has limitations or not. I was able to get my positions and sell a stock using it but that's basically all I've tested.
> 
> I'll try to do proper pull request later.

Thanks Justin... I was able to use this and I updated the Robinhood.py script as such and was able to resolve my authentication error reported as  **"No JSON object could be decoded"** earlier.

The code was updated as per below (I've commented the older code out for reference)

        #"login":  "https://api.robinhood.com/api-token-auth/",
        "login":  "https://api.robinhood.com/oauth2/token/",
        "margin_upgrades": "https://api.robinhood.com/margin/upgrades/",
        "markets": "https://api.robinhood.com/markets/",
        "notification_settings": "https://api.robinhood.com/settings/notifications/",
        "notifications": "https://api.robinhood.com/notifications/",
        "orders": "https://api.robinhood.com/orders/",
        "password_reset": "https://api.robinhood.com/password_reset/request/",
        "portfolios": "https://api.robinhood.com/portfolios/",
        "positions": "https://api.robinhood.com/positions/",
        "quotes": "https://api.robinhood.com/quotes/",
        "user": "https://api.robinhood.com/user/",
        "watchlists": "https://api.robinhood.com/watchlists/",
        "optionsOrders":"https://api.robinhood.com/options/orders/",
        "optionsPositions":"https://api.robinhood.com/options/positions/"
    }

    session = None
    username = None
    password = None
    headers = None
    auth_token = None
    positions = None

    ##############################
    #Logging in and initializing
    ##############################

    def __init__(self):
        self.session = requests.session()
        try:
            self.session.proxies = urllib.getproxies() #py2
        except:
            self.session.proxies = urllib.request.getproxies() #py3
        self.headers = {
            "Accept": "*/*",
            "Accept-Encoding": "gzip, deflate",
            "Accept-Language": "en;q=1, fr;q=0.9, de;q=0.8, ja;q=0.7, nl;q=0.6, it;q=0.5",
            "Content-Type": "application/x-www-form-urlencoded; charset=utf-8",
            "X-Robinhood-API-Version": "1.0.0",
            "Connection": "keep-alive",
            "User-Agent": "Robinhood/823 (iPhone; iOS 7.1.2; Scale/2.00)"
        }
        self.session.headers = self.headers

    def login(self, username, password, mfa_code=None):
        self.username = username
        self.password = password
        self.mfa_code = mfa_code
        #fields = { 'password' : self.password, 'username' : self.username, 'mfa_code': self.mfa_code }
        #fields = { 'password' : self.password, 'username' : self.username }
        
        if mfa_code:
            fields = { 'client_id' : 'c82SH0WZOsabOXGP2sxqcj34FxkvfnWRZBKlBjFS',
                        'expires_in' : 86400,
                        'grant_type': 'password',
                        'password' : self.password,
                        'scope' : 'internal',
                        'username' : self.username,
                        'mfa_code': self.mfa_code }
        else:
            fields = { 'client_id' : 'c82SH0WZOsabOXGP2sxqcj34FxkvfnWRZBKlBjFS',
                        'expires_in' : 86400,
                        'grant_type': 'password',
                        'password' : self.password,
                        'scope': 'internal',
                        'username' : self.username }
        try:
            data = urllib.urlencode(fields) #py2
        except:
            data = urllib.parse.urlencode(fields) #py3
        res = self.session.post(self.endpoints['login'], data=data)
        #res.raise_for_status()
        res = res.json()
        #print(data)
        try:
            #self.auth_token = res['token']
            self.oauth_token = res['access_token']
        except KeyError:
            return res
        #self.headers['Authorization'] = 'Token '+self.auth_token
        self.headers['Authorization'] = 'Bearer ' + self.oauth_token
        return True

**Comment by chiefsmurph** [comment]
noticed this issue as well and opened a PR for the robinhood-node package over at https://github.com/aurbano/robinhood-node/pull/78 to use the oauth2 endpoints in case this is helpful though it looks like its all good.

**Comment by Goldeneye22** [comment]
Thank you for solving this so quick!

**Comment by PlayingGoFish** [comment]
With this new authentication it appears to only allow one API connection per IP address. 
If anyone knows the call to logout that would be appreciated.
I implemented the above changes on my laptop and then when i went to throw it on my server it wouldnt allow another login from the same IP.
I narrowed this down via VPN and it let me log in under a different IP.

Not sure if this will expire at some point. We shall see.

**Comment by justin-pierce** [comment]
> With this new authentication it appears to only allow one API connection per IP address.
> If anyone knows the call to logout that would be appreciated.
> I implemented the above changes on my laptop and then when i went to throw it on my server it wouldnt allow another login from the same IP.
> I narrowed this down via VPN and it let me log in under a different IP.
> 
> Not sure if this will expire at some point. We shall see.

If the 'expires in' field is accurate, it'll expire in 24h -- though certain activity might keep it alive. Definitely something to look into as we may need to occasionally refresh our tokens.

**Comment by justin-pierce** [comment]
derekshreds on reddit filled in info for refreshing token: 

> The json returned when you get the access_token also returns refresh_token.

post to https://api.robinhood.com/oauth2/token/ with:

"refresh_token": [the string from refresh_token]

"grant_type":"refresh_token"

"client_id":"c82SH0WZOsabOXGP2sxqcj34FxkvfnWRZBKlBjFS"

​

This will return a new access_token and refresh_token in json. Not sure if you can manually expire the token / logout. The tokens expire after 86400 seconds, just for everyone's information.

**Comment by chrispykim** [comment]
Anyone seeing the following error even with the above changes? 

> requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.robinhood.com/portfolios/

**Comment by tedchou12** [comment]
works great!! Thank you so much!

**Comment by gautammatta** [comment]
> Anyone seeing the following error even with the above changes?
> 
> > requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.robinhood.com/portfolios/

Yes seeing the same issue. Anybody knows why? Thanks

**Comment by tedchou12** [comment]
@gautammatta 
The file probably not been corrected properly, I uploaded my version here:
https://github.com/tedchou12/Robinhood/blob/master/Robinhood/Robinhood.py
feel free to try it out.

**Comment by edPratt** [comment]
Can someone create a PR for this is they've actually got it working? @desicruizer @justin-pierce

**Comment by edPratt** [comment]
@tedchou12 do you have this working still?

**Comment by edPratt** [comment]
@batcavenet did you just copy past the code he posted? I tried that and still had issues. If you have a working version, can you please create a PR?

**Comment by tedchou12** [comment]
@edPratt 
I think you don't have the endpoint.py file editted.
```def login():
    return "https://api.robinhood.com/oauth2/token/"```
If you have issue trying reinstalling with the package I uploaded, I have it working quite well still.

**Comment by edPratt** [comment]
Update: I got it working! @tedchou12 . I now need to open a pr, but need to request access from @Jamonek I believe. Thanks all

**Comment by tedchou12** [comment]
good good. I am not sure if this is still alive. But feel free to ask me if you need.

**Comment by FergusClare** [comment]
I'm still having a problem logging in.  I updated the Robinhood.py in the Robinhood folder with the one created by @tedchou12.  Still getting the simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0) error.

**Comment by FergusClare** [comment]
My bad.  I hadn't updated the endpoint.py file that @tedchou12 mentioned above.  As soon as I edited that, I was able to login without error.  Thanks!

**Comment by m-deck** [comment]
is anyone able to get this to work with MFA

**Comment by edPratt** [comment]
@tedchou12 @desicruizer @justin-pierce can you guys take a look at my most recent issue? "get_options_data 404". Since you guys seemed to solve this I figured you might be able to dig into the get_options_data function. There are a few changes I had to make to get to the 404 error (bugs in the function unrelated to auth), so check out this branch https://github.com/edPratt/Robinhood/tree/fix-options. Thank you in advance to whoever takes a look!

**Comment by m256** [comment]
Does anyone have a curl command approach to 

> > Ok I think I got it working. Basically you use what I linked to here:
> > > Here's a way to get an 'access_token' from username/pwd: [westonplatter/fast_arrow#13 (comment)](https://github.com/westonplatter/fast_arrow/issues/13#issuecomment-414080185)
> > > But that seems to be different than the 'token' we used to get? Robinhood class has auth_token and oauth_token -- I assume the above returns oath_token, not sure how to get auth_token.
> > 
> > 
> > Then when you set token in authorization header, change from
> > `self.headers['Authorization'] = 'Token ' + self.auth_token`
> > to
> > `self.headers['Authorization'] = 'Bearer ' + self.oauth_token`
> > (make sure you set oath_token from 'access_token' first)
> > edit: my new login call is
> > ` def login(self,
> > username,
> > password,
> > mfa_code=None):
> ```
Does anyone have a **_curl_** command approach to doing this. I have written all my scripts in R and run them using system commands in linux.

**Comment by m256** [comment]
Just figured out the linux curl command way 
[https://github.com/Jamonek/Robinhood/issues/176#issuecomment-504604729](url)
