### ISSUE TITLE
The robinhood market price is not available for quite a while

### ISSUE THREAD

**Issue by batcavenet** [robinhood-unofficial/Robinhood#137]
So the market opens at 8:30 CST- but it's 8:42 and the marketprice is still 0.

Is this something wrong with my code or just the robinhood API doesn't return data until a certain time?

**Comment by batcavenet** [comment]
Umm - so what the heck?

Robinhood Support (Robinhood Help Center) 
Sep 14, 6:47 AM PDT 
Hi Jeremy,
We noticed that you may be trading through an API (Application Programming Interface). We’re excited to offer you commission-free trading, but we can’t allow you to transact with an API.
In the meantime, we’ll need you to take the following steps to keep using Robinhood:
•	Upload a photo of your government-issued I.D. into your Robinhood app when you’re prompted. 
•	Respond to this email with an explanation of your trading and confirmation that you will no longer transact with an API. 
If we haven’t heard from you in 3 days, we may have to prevent you from placing buy orders until we receive your response. If you have any additional questions, please respond to this email and let us know. We’re here to help.
Sincerely,
Robinhood Support

**Comment by batcavenet** [comment]
We don't have a publicly available API. We'll reach out to you directly if we'd like to work with you, and we recommend you follow us on social media for any potential future announcements of a widely available API. We strongly suggest using our mobile or platform for orders.
Currently, we can not allow you to transact with an API. To help clarify the following information below addresses your concern:
There are issues related to the SEC and FINRA regulations that may impact any business plan involving software for trading. 
https://d2ue93q3u507c2.cloudfront.net/assets/robinhood/legal/Robinhood%20Terms%20and%20Conditions.pdf “No part of the Service or Content may be copied, reproduced, republished, uploaded, posted, publicly displayed, encoded, translated, transmitted or distributed in any way (including “mirroring”) to any other computer, server, web site or other medium for publication or distribution or for any commercial enterprise, without Robinhood’s express prior written consent.“
Additionally our User Agreement discusses the following in regards to API specifically.
Section F: “The API Package, including content, is protected under U.S. patent, copyright laws, international treaties or conventions, and other laws and will remain Robinhood’s exclusive property, as applicable.”
Please let me know if you have any further questions.
Sincerely,
Robinhood Support

**Comment by jasonleehodges** [comment]
Very interesting. Would not surprise me if they took active steps to limit external api usage.

**Comment by justin-pierce** [comment]
Yeah this was always a risk of using their private api.

**Comment by penguinshin** [comment]
so does this mean we can't use the api, or is it just a warning?

**Comment by justin-pierce** [comment]
It's clear that they don't want people using their api

**Comment by batcavenet** [comment]
Well- don't ask any questions about it to support ...

**Comment by penguinshin** [comment]
so support only warned/reprimanded you once you asked them?

**Comment by hsauers5** [comment]
This is a real shame. I'll look into spinning something up to fetch current market prices by an external API... I noticed this issue when I ran benchmark comparisons on my fork of the project.

**Comment by GregP83** [comment]
Yeah seems like https://api.robinhood.com/quotes/<ticker_here>/ is permanently not working anymore. Always have 401 http error.

**Comment by hsauers5** [comment]
Greg, please feel free to check out my workaround here: https://github.com/hsauers5/Robinhood/commit/12785fb657db4aace6f2a87dfc1ef0c910f88566

**Comment by GregP83** [comment]
HSauers5 - thanks so much. I started looking into similar solution with worldtradingdata and alphavantage but they both have limits for a daily requests. Your solution works brilliantly.

**Comment by mainstringargs** [comment]
Is it just the ticker data that doesn't work anymore or is the Robinhood API completely disabled now?

**Comment by hsauers5** [comment]
Some functions of it are disabled. I did implement some workarounds to
fetch account data by updating the API endpoints, but I have yet to test
out buying or selling via the API.

**Comment by chiefsmurph** [comment]
I just received the `We’re excited to offer you commission-free trading, but we can’t allow you to transact with an API` Noooo... Come on Robinhood you can allow it.

**Comment by mainstringargs** [comment]
Ah.  That's not good.  Did they email you that?  I guess its time to move completely over to https://alpaca.markets/

**Comment by chiefsmurph** [comment]
> Ah. That's not good. Did they email you that? I guess its time to move completely over to https://alpaca.markets/

Yep, just received it this morning.  Ahhhh.  Come on Robinhood!

**Comment by chiefsmurph** [comment]
I swear they waited until I had a strategy that worked before they sent me that.

**Comment by CTJyeh** [comment]
That is disappointing.  For a "customer" centric company, they can hopefully do better

**Comment by mainstringargs** [comment]
I wonder if they ever plan to have an "official" API

**Comment by chiefsmurph** [comment]
Wow can you believe this?!  Robinhood has blocked my ability to even login.  I responded to their email and politely asked for an extension as "I made other arrangements" for my API trading.  I did not hear back from them, but this morning - right at market open - they blocked my ability to trade.  They better not think they are taking my funds.

**Comment by codesociety** [comment]
I don't think it's just you... they maybe having legitimate issues. I am having the same problem with the API. I am also seeing weird behaviors using the phone app.
It would be nice if they can inform people of possible issues they are having.

**Comment by codesociety** [comment]
found the following link which outlined the possible issue...

https://downdetector.com/status/robinhood

**Comment by codesociety** [comment]
I was just allowed to log in using the API... Just a few minutes again.

**Comment by chiefsmurph** [comment]
@code

thanks for the heads up.  you are absolutely right.  I was jumping to conclusions.  Looks like it is sorted out now.
