### ISSUE TITLE
Login endpoint gives 404, still not working. Someone please create PR

### ISSUE THREAD

**Issue by edPratt** [robinhood-unofficial/Robinhood#138]
Apparently other people have been able to get this working (per the previous post), so if that is true, someone should create a PR as this project is virtually useless without being about to login.

**Comment by FergusClare** [comment]
Echo of @edPratt 

I tried updated source with the oAuth data provided in another chain to no avail.  Unable to login.

**Comment by vlall** [comment]
Same issue here.

**Comment by blindedjoy** [comment]
Someone should fix this: I think the info is here: https://www.reddit.com/r/algotrading/comments/9fatem/robinhood_api_login_issues/

**Comment by edPratt** [comment]
I've got it working, but I'm not sure how to open a pr. I try to push my branch, but I don't have permission to contribute to the project. Anyone? @FergusClare @blindedjoy @vlall

**Comment by blindedjoy** [comment]
can you email me the solution? hnjoy@mac.com

**Comment by edPratt** [comment]
@blindedjoy https://github.com/edPratt/Robinhood/tree/hotfix-404

**Comment by edPratt** [comment]
Am I wrong, or should I be able to push a branch to this repo, and then open a pr for the admin to approve? When I try to push my hotfix-404 branch to a branch of the same name, I get a permission error.

**Comment by FergusClare** [comment]
@Jamonek please see note from @edPratt above.  Most of us have been able to manually fix this using changes suggested in another thread.  Would be great to get Ed's fixes on the master branch.

**Comment by vlall** [comment]
> Am I wrong, or should I be able to push a branch to this repo, and then open a pr for the admin to approve? When I try to push my hotfix-404 branch to a branch of the same name, I get a permission error.

the repo may not be open to public PRs

**Comment by Jamonek** [comment]
If you can get the PR open, I can merge the fix. 

Best,

Jamone

**Comment by vlall** [comment]
> If you can get the PR open, I can merge the fix. Best, Jamone
> […](#)
> On Oct 2, 2018, at 2:39 PM, Vishal ***@***.***> wrote: Am I wrong, or should I be able to push a branch to this repo, and then open a pr for the admin to approve? When I try to push my hotfix-404 branch to a branch of the same name, I get a permission error. the repo may not be open to public PRs — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

PR opened

**Comment by edPratt** [comment]
@vlall I'm not sure this fix actually works. The login function no longer breaks, but nothing else works now. I'm getting a lot of authentication issues with most functions.

**Comment by aamazie** [comment]
See issue #147

**Comment by aamazie** [comment]
@edPratt From what I can tell, there seems to be some interference/re-routing to the Login Prompt function with this fix. The code of your fix looks better than mine, depsite the fact that you should change your Log Out endpoint URL as well.

**Comment by aamazie** [comment]
@edPratt @vlall The authentication works for things that don't pertain directly to one's own account. If the function has to go through an endpoint that has to access information particular to one's own account, it doesn't work. So you can get stock information, like quotes, but you can't get your own equity or trade history..

**Comment by aamazie** [comment]
In the __init__ method, the "self.auth_method = self.login_prompt" is called again for some reason when accessing endpoints particular to one's account. I tried changing it to self.login instead, but I get "TypeError: login() missing 2 required positional arguments: 'username' and 'password'", meaning that the payload with the username and password isn't being remembered... This was tested by printing out a stock's information, which worked, meaning I was logged in, and then the error is caused when trying to access my order history afterward. A bit confused about what's going on here and help would be appreciated.

**Comment by aamazie** [comment]
Since this group's title isn't technically accurate any longer, I'm going to be posting in #147 ideally

**Comment by aamazie** [comment]
We finally got it working thanks to folks in #147. Created a PR #150 for @Jamonek that fixes the login problems for stock data as well as account-particular data and access, as well as the broken cancel_order function.
