### ISSUE TITLE
Depth of markets

### ISSUE THREAD

**Issue by firefox0x** [robinhood-unofficial/Robinhood#142]
Is there a function to get the market depth of a particular stock?  So far, only the best bid and ask price and quantities are available.  Is it possible to see the 2nd best, 3rd best price and quantities etc?

**Comment by m-deck** [comment]
That would be considered "Level 2" market data:

https://www.thebalance.com/order-book-level-2-market-data-and-depth-of-market-1031118

I believe there would be an additional cost to Robinhood if they provided this level of data, so it makes sense that they wouldn't provide it.
