### ISSUE TITLE
bid/ask data showing all zeroes

### ISSUE THREAD

**Issue by m-deck** [robinhood-unofficial/Robinhood#143]
is anyone else having this problem? all bid/ask prices and sizes appear to be returning zeroes for me on the quote_data method.

**Comment by firefox0x** [comment]
yes.  its back now.  whatever you do, do not contact Robinhood support XD

**Comment by m-deck** [comment]
I'm still getting zeroes. Is this just an intermittent problem / does it start working mid-day or something? Can someone provide a code example that successfully provides non-zero results?

**Comment by m-deck** [comment]
Using the web client and monitoring via Chrome dev tools seems to show same API response of zeroes

![bid ask](https://user-images.githubusercontent.com/12189943/46675076-46a31200-cba3-11e8-938e-ad00b409c649.png)

**Comment by firefox0x** [comment]
Not sure, it works sometimes and sometimes it doesn't.  also the data seems to lag by quite a bit.  quote_data is completely unusable right now.

**Comment by adi0321** [comment]
does anyone observe a delayed ask price? Last traded price seems to be ahead of ask/bid prices? 

          DATE |      TIME |     TICK   | last_tra     |   ask_pr   | ask_size |   bid_pr | bid_size |       volume |     
2019/01/24 | 15:18:10 |     NVDA | 158.0000 | 157.3400 |      200   | 157.2700 |      100 |  6,970,274.0 |
