### ISSUE TITLE
Unable to log in with provided credentials. - Non-Alphanumeric Characters

### ISSUE THREAD

**Issue by monolid** [robinhood-unofficial/Robinhood#144]
I am trying to log in with the API, but I am no longer able to. 

rh = Robinhood()
logged_in = rh.login(username='', password='')
print(logged_in)

My username does have NON alphanumeric characters--is this what is causing the issue?

What solutions are there for me?

**Comment by m-deck** [comment]
@Mr-Monolid I had the same issue but with non alphanumeric characters in the password. It's the URL encoding that appeared to be problematic. See #145 for my suggested fix.

**Comment by nkulung** [comment]
Having the same issue, password also contains a non alphanumeric character, I believe this is a requirement when signing up for the site. 

`raise RH_exception.LoginFailed()
Robinhood.exceptions.LoginFailed`

**Comment by jaschlak** [comment]
I am receiving a login error as well. I thought it might be a 2 factor problem but I see there is a separate error in the code for that , I am using Spyder3 and when I look at line 118 on the Robinhood.py file, it appears to be an HTTP error? I am not too familiar with it. 


Here is the error the console reported:
------------------------------------------------
  File "FilePath", line 118, in login
    raise RH_exception.LoginFailed()

LoginFailed
------------------------------------------------



Here is line 118 from Robinhood.py:
------------------------------------------------
            res = self.session.post(endpoints.login(), data=payload, timeout=15)
            res.raise_for_status()
            data = res.json()
        except requests.exceptions.HTTPError:
            raise RH_exception.LoginFailed()
------------------------------------------------

Any help would be appreciated or just knowing the API doesn't work anymore (although it seems like a lot of people have not problem so I doubt that)

Thanks!

**Comment by jaschlak** [comment]
I now see @m-deck's response. Now that I think of it I have a non-alpha numeric character and that might fix the issue. I will give it a shot and report back if it fixes the issue.

**Comment by aamazie** [comment]
This is not the whole/actual issue. Please see Issue #147

**Comment by aamazie** [comment]
We finally got it working thanks to folks in #147. Created a PR #150 for @Jamonek that fixes the login problems for stock data as well as account-particular data and access, as well as the broken cancel_order function.
