### ISSUE TITLE
LogIn/Authetication Deprecated

### ISSUE THREAD

**Issue by aamazie** [robinhood-unofficial/Robinhood#147]
Robinhood recently changed their authentication code and so this API's Log In function and endpoint are out of date. 

I made changes per the suggestions on this page: https://www.reddit.com/r/algotrading/comments/9fatem/robinhood_api_login_issues/

However, the changes only allow me to access information that isn't particular to my account, like stock quotes, but when I go to check something like my order history it prompts an input of my username and password again and after inputting the correct info, my order history returns: {'detail': 'Authentication credentials were not provided.'}.

I have removed my queued pull request, as I had fixed the cancel_order function months ago and @Jamonek had neglected to merge it and so it was still open. I will re-open a pull request when my code is completely functional. In the meantime, please check out my code and clone my repository to do tests so that we can get this API back up and running again like it should.

The changes I made were changing the Log In and Log Out endpoint URLs in the Endpoints.py file and also, in the Robinhood.py file, changing the Login function's payload and replacing the "Token" with "Bearer".

I do not know where to find Robinhood's 200k line JavaScript code file that the Reddit thread cites for this update, and so I'm at an impasse when it comes to continuing to fix the authentication.

From what I can tell, there seems to be some interference/re-routing to the Login Prompt function with this fix.

**Comment by aamazie** [comment]
In the init method, the "self.auth_method = self.login_prompt" is called again for some reason when accessing endpoints particular to one's account. I tried changing it to self.login instead, but I get "TypeError: login() missing 2 required positional arguments: 'username' and 'password'", meaning that the payload with the username and password isn't being remembered... This was tested by printing out a stock's information, which worked, meaning I was logged in, and then the error is caused when trying to access my order history afterward. A bit confused about what's going on here and help would be appreciated.

**Comment by tossthedice** [comment]
Someone fix it please!!!!

**Comment by tossthedice** [comment]
@aamazie I used your code to try to login. Seems like it should work according to the Reddit post you referenced, but doesn't seem to be working for me. I tried to login with:

logged_in = my_trader.login(username='blahblahblahblahblah', password='blahblahblahblah')

JSONDecodeError                           Traceback (most recent call last)
<ipython-input-8-f0b09ee0ff46> in <module>
----> 1 logged_in = my_trader.login(username='blahblahblah', password='blahblahblah')

~/anaconda3/envs/my_env_36/lib/python3.6/site-packages/Robinhood/Robinhood.py in login(self, username, password, mfa_code)
    124         res = self.session.post(endpoints.login(), data=data)
    125         #res.raise_for_status()
--> 126         res = res.json()
    127         #print(data)
    128         try:

~/anaconda3/envs/my_env_36/lib/python3.6/site-packages/requests/models.py in json(self, **kwargs)
    890                     # used.
    891                     pass
--> 892         return complexjson.loads(self.text, **kwargs)
    893 
    894     @property

~/anaconda3/envs/my_env_36/lib/python3.6/json/__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    352             parse_int is None and parse_float is None and
    353             parse_constant is None and object_pairs_hook is None and not kw):
--> 354         return _default_decoder.decode(s)
    355     if cls is None:
    356         cls = JSONDecoder

~/anaconda3/envs/my_env_36/lib/python3.6/json/decoder.py in decode(self, s, _w)
    337 
    338         """
--> 339         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    340         end = _w(s, end).end()
    341         if end != len(s):

~/anaconda3/envs/my_env_36/lib/python3.6/json/decoder.py in raw_decode(self, s, idx)
    355             obj, end = self.scan_once(s, idx)
    356         except StopIteration as err:
--> 357             raise JSONDecodeError("Expecting value", s, err.value) from None
    358         return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by anthonykrivonos** [comment]
Not sure if any progress was made on this topic, but here's my solution:

1. In `Robinhood/endpoints.py`, change the `login` method to return `"https://api.robinhood.com/oauth2/token/"`.
2. Change the `payload` dict in the `login` function in `Robinhood/Robinhood.py` to:
   `payload = {
            'password': self.password,
            'username': self.username,
            "grant_type": "password",
            "client_id": "XXXXXXXXXXXXXXXXXX"
        }`, where `'XXXXXXXXXXXXXXXXXX'` is your client ID.

Viola!

**Comment by aamazie** [comment]
@anthonykrivonos Still can't login to account/portfolio-particular things like order history, etc. There seems to be some kind of thing with OAuth2 that I need to look into that is causing this problem I think.

**Comment by anthonykrivonos** [comment]
@aamazie Ah, sorry for missing that. Seems like so many endpoints here need an update. User `aurbano` did some great work with the [Node.js wrapper of Robinhood's API](https://github.com/aurbano/robinhood-node/blob/master/src/robinhood.js), and it seems to have the new server calls implemented. I'm going to take a crack at refactoring this repo and will likely submit a pull request once everything works as it should.

**Comment by TheScienceOfSciences** [comment]
where can i find my client_id?

**Comment by TheScienceOfSciences** [comment]
the reddit is saying to use

"client_id":"c82SH0WZOsabOXGP2sxqcj34FxkvfnWRZBKlBjFS"

is this what you guys are using or is it user specific?

**Comment by anthonykrivonos** [comment]
@TheScienceOfSciences that's the one currently being used by the Node.js alternative, so I will make a bold supposition and say it's safe to use it. I couldn't really find any documentation on Robinhood client keys, which is another issue altogether :)

**Comment by TheScienceOfSciences** [comment]
@anthonykrivonos created pull request with working login and portfolio based on the changes you posted earlier. Seems the api returns 'access_token' instead of 'token' for logging in. Also need to append to "Bearer " instead of "Token " now.

**Comment by anthonykrivonos** [comment]
@TheScienceOfSciences I just saw your pull request, but there were still several nonworking methods in there that I don't recommend merging. On the other hand, I'd already submitted pull request #149 that fixes every issue you described, with the few fixes for other calls that weren't working. Please review it; I hope @Jamonek reviews it too and perhaps we can get that merged.

**Comment by aamazie** [comment]
@TheScienceOfSciences #149 actually still has a bug. I fixed it and submitted my own PR #150 with a fully-fixed cancel_order function as well. Thank you for your contributions! My initial fix was very similar to yours, but without changing "token" to "access_token". Huge help. It finally works! @Jamonek Please merge this!

**Comment by anthonykrivonos** [comment]
@aamazie @TheScienceOfSciences great work, team. 👍 hope this is seen and merged ASAP.

**Comment by TheScienceOfSciences** [comment]
Thanks guys. This is my first time contributing on Github. Glad I was able to help.

**Comment by aamazie** [comment]
@TheScienceOfSciences Really, thank you!

**Comment by anthonykrivonos** [comment]
Also, if you guys are interested, I'm currently implementing this repo in [one of my projects](https://github.com/anthonykrivonos/Quantico). My hope is to grow the project into a library for trading algorithms, but for now, I have implemented candlestick plotting and line graphs taken from a slightly modified `get_historical_quotes` function (the one in #149 and #150 may not be working). Check it out whenever you can.

**Comment by duncanleung** [comment]
👏!

Also, @anthonykrivonos does your Quantico project's fork of `Jamonek/Robinhood` have these login fixes?

It seems like this repo isn't really actively maintained. Was wondering if your fork would be the way to go moving forward.

**Comment by anthonykrivonos** [comment]
@duncanleung Thanks, Duncan! Yep, [Quantico](https://github.com/anthonykrivonos/Quantico) has them but I'm making sure to incorporate all of the changes I'm making in that repo to my fork of Robinhood (#149). @aamazie There were multiple more fixes I had to make this morning, such as the `historicals` function and `place_order`. I'm sure there are a handful more bugs I've missed, and please let me know if you find anything. I believe **it's best to use my fork**, at least for now, since it doesn't seem that these pull requests are going to be merged anytime soon.

**Comment by aamazie** [comment]
@anthonykrivonos Use my cancel_order function. The one that everyone has forked from the master is totally broken.

**Comment by anthonykrivonos** [comment]
@aamazie Sure! I’ll update my fork in a few hours with your fixes (+ give you contribution credit ofc).

**Comment by aamazie** [comment]
Yeah, because this was pretty much me trying to place and cancel orders before I fixed that function: https://www.youtube.com/watch?v=gbu88CKkEzI

**Comment by aamazie** [comment]
Also, a bunch of you guys are importing the exceptions with "import exceptions as RH_exception", which doesn't work for me. I use "from . import exceptions as RH_exception".

**Comment by anthonykrivonos** [comment]
@aamazie That video's gold––don't know why I even expected a video of you trying to debug the endpoints 😅 Anyway, just implemented your changes into #149! Also, what version of Python are you running?

**Comment by aamazie** [comment]
Python 3.6. Also, I updated the place_buy_order and place_sell_order functions. Added automatic ask/bid pricing for buy/sell order functions respectively if the price isn't asked. Robinhood has pretty bad slippage, so this might be useful. The buy order had "bid_price" as a variable, which doesn't make sense because you use ask_price for buying and bid_price for selling if I'm not mistaken.

**Comment by aamazie** [comment]
@anthonykrivonos Is placing an order working for you?

**Comment by aamazie** [comment]
I may have to open a new issue about the order placing. I've been getting this error: "400 Client Error: Bad Request for url: https://api.robinhood.com/orders/" I think it's because the endpoint needs to take an order_id but I'm not sure

**Comment by anthonykrivonos** [comment]
@aamazie Yep. Check my PR––I already fixed that issue. The `submit_order` requires `price` in the request. I default it to the `bid_price` of the current quote.

**Comment by aamazie** [comment]
@anthonykrivonos I split the submit_order into submit_buy_order function with price defaulting to the ask price and a submit_sell_order function with the price defaulting to the bid price. I then changed the functions that called the submit_order. I'm going to do more testing when markets open this week and I'll let you know how it goes.

**Comment by anthonykrivonos** [comment]
@aamazie Sounds great, I deployed a financial algo yesterday morning on [Quantico](https://github.com/anthonykrivonos/Quantico) and completed 3 buy orders and 4 sell orders through this API with my own fork. Let me know how it goes.

**Comment by aamazie** [comment]
For the record, to anyone reading this, @TheScienceOfSciences was the one who really fixed the LogIn function in full. The bug I fixed afterward in my PR, aside from the cancel_order, was how the endpoints were imported, which apparently worked for others but not for me. Just wanted to reiterate my gratitude and restate for his credit.

**Comment by anthonykrivonos** [comment]
@aamazie Just to make it clear for everyone reading this too, the login fix and all other fixes in #149, besides your `cancel_order` fix, were implemented by myself. Credit was rightly given in the `CONTRIBUTORS` file. 👍

**Comment by TheScienceOfSciences** [comment]
@aamazie I appreciate the credit man! But I wouldn’t have been about to get it working without @anthonykrivonos and his work. It would be nice of you guys to include me in the contributors list as I think that would be accurate. Cheers!

**Comment by aamazie** [comment]
@anthonykrivonos I finished the submit buy and submit sell functions and deprecated the place order functions, as those didn't seem to be working. You, or anyone else, can use my code in yours if you want. As I said, now the submit buy uses the ask price and the submit sell uses the bid price. #150
