### ISSUE TITLE
get_options returns zero data

### ISSUE THREAD

**Issue by pewpewmcgee** [robinhood-unofficial/Robinhood#156]
Its been a while since i have tested my code, and i recently pulled down the latest from the repo. While trying to pull down options data:

`my_trader = Robinhood()
logged_in = my_trader.login(username="email@address.com", password="mypassword", mfa_code = mfa_code)
print(my_trader.get_options('SPY', '2018-11-23', 'CALL'))`

This prints out `[]`. Is this an issue with my code or the api lib?

**Comment by avidbrandy** [comment]
use 'call' instead of 'CALL' and it should work.
