### ISSUE TITLE
No module named 'exceptions'

### ISSUE THREAD

**Issue by helloman1802** [robinhood-unofficial/Robinhood#161]
Hello all,

I just ran the installer and got this error when importing Robinhood:
```
>>> import Robinhood
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/malachi/Documents/BrightQuant/Robinhood/Robinhood/__init__.py", line 4, in <module>
    from Robinhood.Robinhood import Robinhood
  File "/home/malachi/Documents/BrightQuant/Robinhood/Robinhood/Robinhood.py", line 20, in <module>
    import exceptions as RH_exception
ModuleNotFoundError: No module named 'exceptions'
```
I saw that this was supposed to be fixed on #35 , but it seems that the issue has reappeared. 

Thanks,
Malachi

**Comment by evanlee123** [comment]
I had the exact same problem for a while. After looking through the code, I noticed that in Robinhood.py the import statements had:
`#Application-specific imports
import exceptions as RH_exception
import endpoints
`

I changed that to:
`#Application-specific imports
from . import exceptions as RH_exception
from . import endpoints
`

There is also a pull request that already addresses this: [#155](https://github.com/Jamonek/Robinhood/pull/155)
