### ISSUE TITLE
quote_data fails with InvalidTickerSymbol - quotes endpoint requires auth token now

### ISSUE THREAD

**Issue by trevorwelch** [robinhood-unofficial/Robinhood#167]
GET requests for quotes now require that you pass your access token. 

For anyone looking for a quick fix to the problem, in your `quote_data` and `quotes_data` functions in `Robinhood.py`, replace:
```
req = requests.get(url, timeout=15)
```
with:
```
req = requests.get(url, headers=self.headers, timeout=15)
```

which will pass your auth token with your quotes request.

For any future PR, make sure to change the `InvalidTickerSymbol()` raise, because it's not really accurate.

s/o to https://github.com/Ladinn/algotrader/issues/11 for the idea!

**Comment by GoldenEye22** [comment]
I just tried this, but what do I change in InvalidTickerSymbol() or do we just remove it completely?

**Comment by trevorwelch** [comment]
> I just tried this, but what do I change in InvalidTickerSymbol() or do we just remove it completely?

I left this bit alone for now, because it's not exactly clear what the best route to make this more informative is:
```
        except requests.exceptions.HTTPError:
            raise RH_exception.InvalidTickerSymbol()
```

You could make a new exception class in `exceptions.py` that better describes the error here (`MissingBearerToken()` or something), and then raise that instead of `InvalidTickerSymbol()`.

**Comment by GoldenEye22** [comment]
Ok, making your change (req = requests.get(url, headers=self.headers, timeout=15) )did not fix the InvalidTickerSymbol() from being triggered in my Robinhood.py

**Comment by trevorwelch** [comment]
> Ok, making your change (req = requests.get(url, headers=self.headers, timeout=15) )did not fix the InvalidTickerSymbol() from being triggered in my Robinhood.py

Interesting. Works for me, I wonder if you're using an older version? 

What does your `def login` function look like?

**Comment by GoldenEye22** [comment]
def login(self,
              username,
              password,
              mfa_code=None):
        """Save and test login info for Robinhood accounts

        Args:
            username (str): username
            password (str): password

        Returns:
            (bool): received valid auth token

        """

        self.username = username
        self.password = password
        payload = {
			'client_id': 'c82SH0WZOsabOXGP2sxqcj34FxkvfnWRZBKlBjFS',
			'expires_in': 86400,
			'grant_type': 'password',
			'password': self.password,
			'scope': 'internal',
			'username': self.username
        }

        if mfa_code:
            payload['mfa_code'] = mfa_code

        try:
            res = self.session.post('https://api.robinhood.com/oauth2/token/', data=payload, timeout=15)
            res.raise_for_status()
            data = res.json()
        except requests.exceptions.HTTPError:
            raise RH_exception.LoginFailed()

        if 'mfa_required' in data.keys():           # pragma: no cover
            raise RH_exception.TwoFactorRequired()  # requires a second call to enable 2FA

        if 'access_token' in data.keys():
			self.oauth_token = data['access_token']
			self.headers['Authorization'] = 'Bearer ' + self.oauth_token
			return True

        return False

**Comment by GoldenEye22** [comment]
Yes, you might be right. I'm on my work computer and have updated it.

**Comment by trevorwelch** [comment]
Hmm, not sure what the issue could be there. It looks like `self.headers` should include your `access_token` correctly, all I'm doing is passing that with my quotes call.

**Comment by GoldenEye22** [comment]
@trevorwelch I see why it wasn't working. Quotes used to work without login. I log off at points in my code, so I need to just stay logged in all the tie now. Thank you for this fix!

**Comment by pgordon9** [comment]
Awesome @trevorwelch! Can we get this fix merged to master??

**Comment by trevorwelch** [comment]
> Awesome @trevorwelch! Can we get this fix merged to master??

I'll have a go at making a PR  😅

**Comment by AlexGoico** [comment]
Still failing for me. Integrating the `headers=self.headers` argument doesn't fix the error. I merely obtain a top level stack trace 404 error: 
```
HTTPError: 404 Client Error: Not Found for url: https://api.robinhood.com/quotes/spy/
```

accompanied with the `InvalidTickerSymbol` error generated within the catchall HTTPError within the function.

I am using `.quote_data('spy')`

**Comment by AlexGoico** [comment]
Found the issue I think. The issue lies in the fact that the ticker must also be uppercase 😐in addition to passing the headers as listed above.

**Comment by mcsj120** [comment]
@trevorwelch Thanks for the fix! Any idea why it hasn't been merged with the master yet?

**Comment by trevorwelch** [comment]
> @trevorwelch Thanks for the fix! Any idea why it hasn't been merged with the master yet?

I do not know why it hasn't been merged. There are constant little fixes in chasing around an private/'unofficial' API like this though, so it would be nice if there was an active maintainer.

**Comment by Jamonek** [comment]
Thank you for your work, @trevorwelch. I’m reviewing the open PRs today
