### ISSUE TITLE
Unable to login to my account

### ISSUE THREAD

**Issue by rachitgarg91** [robinhood-unofficial/Robinhood#177]
I am not able to log into my robinhood account with my username/password. I am using example.py
Do you know what might be going on?

Traceback (most recent call last):
  File "example.py", line 6, in <module>
    my_trader.login(username="blahblah",password="blahblah")
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Robinhood/Robinhood.py", line 120, in login
    raise RH_exception.LoginFailed()

**Comment by BattulgaTS** [comment]
I'm getting same error not sure why.

**Comment by TheCrockett** [comment]
It's related to https://github.com/Jamonek/Robinhood/issues/176

They are working on a fix

**Comment by hanzorama** [comment]
There is a lot of information to sift through there. Is the solution to implement the mfa_code generate section into the Robinhood class?
