### ISSUE TITLE
quote_data being weird

### ISSUE THREAD

**Issue by viaConBodhi** [robinhood-unofficial/Robinhood#178]
Has anyone noticed the API does not return stock prices first thing in the morning...like 9am-10am-ish...anyone know what's happening with this? Code works fine later morning/evening so does not seem to be an issue with the actual code.

**Comment by aamazie** [comment]
There may be some additional log in needed before accessing stock quotes. The first trade of the day was doing this. Are you doing anything after looking for stock quotes in the morning that you may be putting in an additional log in for?

Also, I haven't been experiencing this yet.

**Comment by GoldenEye22** [comment]
I was thinking something needed to be refreshed in the morning. My code has been running continuously and I noticed that it wasn't working at 9:40ish. I was going to investigate tonight. You defiantly need to log in again in the morning to get quotes, but even after doing that something was failing. I am doing try except and wasn't reporting the error message.

**Comment by viaConBodhi** [comment]
@aamazie Could you explain what you mean by "first trade of the day was doing this"? 

I first noticed this since stock prices are built into some other functions I'm working with so I tested by starting an entirely new kernel and simply logged in to RH and tried to get several stocks one-by-one and all were returning 0. I typically use the Fast_Arrow package but even tried with Jamonek (which is basically the same) and both have been returning 0. Starts working later in the morning and other functions work, like getting my data. Interesting though you have not experienced this issue. Have you tried pulling stock prices first thing after 9am?

**Comment by aamazie** [comment]
If they're all returning 0, maybe the stock market is just having a really bad day...

That's a joke.


This morning I it seemed to be working for me.

If you look at my repo, the execution of the parent order-placing functions will have a try/except at the bottom to check if there needs to be an additional login. In rewriting all of the authentication code, I implemented a function called auth_method(), which should do the trick of logging in to an additional request.

**Comment by aamazie** [comment]
Ah, wait! I am having issues, and worse than yours. In testing getting quote data, I'm getting this error:


    quotes = my_trader.quote_data(chosen_one)

    if stock.find(',') == -1:
AttributeError: 'list' object has no attribute 'find'

**Comment by viaConBodhi** [comment]
Or it could indicate a really good time to buy the FANG stocks if they've all dropped to 0 (also joking). I'll checkout your code base for the additional logging but wouldn't that additional requirement be consistent  for all calls no matter what time of day since I'm actually returning the bid/asked, just later in the AM? If things are working for you in the AM then I'll keep digging for bugs.

**Comment by viaConBodhi** [comment]
I'm not getting an error...I'm getting a return close to what's below (it's working now so had to fill in the 0 from memory of what it looked like this morning). Returns work...just missing data. 

{'adjusted_previous_close': '0',
 'ask_price': '0',
 'ask_size': '0',
 'bid_price': '0',
 'bid_size': 0,
 'has_traded': True,
 'instrument': 'https://api.robinhood.com/instruments/ae324050-bc65-4b48-89da-307ef014f1ef/',
 'last_extended_hours_trade_price': None,
 'last_trade_price': '164.702500',
 'last_trade_price_source': 'nls',
 'previous_close': '169.000000',
 'previous_close_date': '2019-05-09',
 'symbol': 'ROK',
 'trading_halted': False,
 'updated_at': '2019-05-10T14:48:14Z'}

**Comment by aamazie** [comment]
Did this only happen today? Maybe they were screwing around over at Robinhood. The instrument came back as a list for me.... I'm 99% sure it wasn't a dictionary in a list before. I changed my repo to handle that. I also rewrote my quote_data function so that it takes either the stock instrument or a string of the stock's symbol and cleaned it up a bit.

**Comment by aamazie** [comment]
Yeah, make that 100%.

**Comment by aamazie** [comment]
They were probably doing some kind of weird update this morning. We'll see what happens tomorrow.

**Comment by GoldenEye22** [comment]
I know based on my code triggering on a change that robinhood updates all the previous days data (such as previous close price) at 9:30am. So I suppose we can assume they update other stuff too.

**Comment by aamazie** [comment]
Also, I would love to buy FANG stocks for $0. I would buy a lot. I should make an algorithm to do that for when this happens again.

**Comment by GoldenEye22** [comment]
just curious but are you guys day trading with the API based on your own algorithms? I just use it to collect long term data and to send messages to my phone about the data or the stocks performance today. Not as exciting I know ...

**Comment by aamazie** [comment]
Yeah, I run algos.

**Comment by aamazie** [comment]
@viaConBodhi will you change the title of the issue to something like "quote_data being weird" in case other people are having issues? Want to make sure they can get here.

**Comment by aamazie** [comment]
I had to fix a bug with the quote_data in my repo today. Just a heads up if anyone's using it.

**Comment by viaConBodhi** [comment]
@aamazie sure thing...title has been updated. Tried running it this morning and getting the following:

{'adjusted_previous_close': '166.490000',
 'ask_price': '0.000000',
 'ask_size': 0,
 'bid_price': '0.000000',
 'bid_size': 0,
 'has_traded': True,
 'instrument': 'https://api.robinhood.com/instruments/ae324050-bc65-4b48-89da-307ef014f1ef/',
 'last_extended_hours_trade_price': '160.850000',
 'last_trade_price': '160.850000',
 'last_trade_price_source': 'consolidated',
 'previous_close': '166.490000',
 'previous_close_date': '2019-05-10',
 'symbol': 'ROK',
 'trading_halted': False,
 'updated_at': '2019-05-13T20:09:19Z'}

Just pulling data for one stock outside of any algo...Going to keep checking to see when starts back up again. Still need to do some bug digging to make sure I'm not missing something. Would be interesting to see if 9:30am is a trigger like @GoldenEye22 mentioned. @GoldenEye22 I've been using for algo and for research. My models also pull from a few other sources outside of RH.

**Comment by viaConBodhi** [comment]
Just realizing that the API may not pull premarket...wondering if that maybe what is happening.

**Comment by viaConBodhi** [comment]
9:53 and returning numbers...interesting

**Comment by aamazie** [comment]
How their API updates things can be weird sometimes. I've had to code for things like the order execution dithering back and forth between updating just afterward. There may be a delay in bid and ask price at the beginning of the day in pulling the JSON. Not sure what to do about this within our API. I know that it actually does place orders fine though. But unfortunately it's not at a 0 ask price.

**Comment by aamazie** [comment]
Actually, it seems like it wouldn't be able to place orders fine. I haven't placed an order during that time in a couple of days, so I can't speak for today or yesterday. I'll do more tests tomorrow.

**Comment by viaConBodhi** [comment]
I've been using the "ask" as a base for limits since the stuff I'm working on is pretty dependent on the up to the second price to determine profitability. I've also noticed the API has some latency when compared to what is shown in the app. Looks like it's one minute behind the feed going to the app. Been considering baking in selenium as a validation on results since it's much slower then the API but can be used for smaller instances.

**Comment by GoldenEye22** [comment]
I haven't gotten a quote to work all day, worked yesterday. No idea what the issue is.

**Comment by aamazie** [comment]
@GoldenEye22 Just took a look at your repo. Check my repo and what I did to the quote_data() function. Also, like I said, RH delivers the instrument in a list now, so I handled that as well by returning the [0] of the instrument.

**Comment by GoldenEye22** [comment]
Yes, I was using yours, but I had to add a little additional flavor to it:

def quote_data(self, stock=''):
        """Fetch stock quote

            Args:
                stock (str or dict): stock ticker symbol or stock instrument

            Returns:
                (:obj:`dict`): JSON contents from `quotes` endpoint
        """

        if isinstance(stock, dict):
            if "symbol" in stock.keys():
                url = str(endpoints.quotes()) + stock["symbol"] + "/"
        elif isinstance(stock, str):
            url = str(endpoints.quotes()) + stock + "/"
        elif isinstance(stock, unicode):
            url = str(endpoints.quotes()) + str(stock) + "/"    
        else:
            raise RH_exception.InvalidTickerSymbol()

        #Check for validity of symbol
        try:
            req = self.session.get(url, headers=self.headers, timeout=15)
            req.raise_for_status()
            data = req.json()
        except requests.exceptions.HTTPError:
            raise RH_exception.InvalidTickerSymbol()


        return data

**Comment by aamazie** [comment]
Oh nice. That's weird, though. Mine is currently working..

**Comment by aamazie** [comment]
Are you getting 0s as the values or an error?

**Comment by GoldenEye22** [comment]
It is because I am using python 2. Str and unicode are seen as different base types in 2.

**Comment by aamazie** [comment]
With my current repo, this works:
    mystock = my_trader.instrument("TSLA")
    quotes = my_trader.quote_data(mystock)
    print(quotes)

**Comment by aamazie** [comment]
Seems like there's some translation to Python 2 still for you.

**Comment by GoldenEye22** [comment]
Well technically I doing something like this:

quote_data = trader.quote_data(row_verify['symbol'])

Where row_verify is a fetch from a sqlite database and the symbol is stored as unicode. I just edited Robinhood.py because it only required 2 lines of code where converting all the unicode to str would have been a lot of changes in my code. I need to switch to python 3 anyways.

What you posted works in python 2:
`mystock = my_trader.instrument("TSLA")
quotes = my_trader.quote_data(mystock)
print(quotes)`

**Comment by viaConBodhi** [comment]
Built a function to check every minute until the data populates and today it reported the missing data populated at 9:47am this morning. Yesterday I did it manually. This was for only one stock though...Next step is to test with several different stocks to see if the population is per stock or across the board.

**Comment by aamazie** [comment]
I noticed it too.

I need to code for catching this with the order placing functions because they defer to the ask/bid price when no price is given. I'll do something like if the ask/bid is 0, use the last traded price. It will suck for when the ask is really 0, but what can you do.

**Comment by viaConBodhi** [comment]
Not too much other than scrape another platform with "up to date" info and use this for any algo...which is where I'm currently headed as a QA since my stuff is pretty time dependent based on slight margins. Good to know where the parameters are with this API though.

**Comment by aamazie** [comment]
Maybe another API for that data then, like Morningstar or something

**Comment by aamazie** [comment]
Made the updates to my repo if anyone's interested.

**Comment by viaConBodhi** [comment]
Working on something like that now...thanks for the update on your repo. Been pricking a few things off your base. I need to get mine updated as it uses a different authentication (email) but uses a wrapper that ties together other RH repos since the keys are the same no matter what repo you're using but the functions used between repos are different. Sort of a "one ring" / central authentication kind of thing.

**Comment by viaConBodhi** [comment]
Confirmed the API does not post "ask" until (today it was 9:46 so most likely about 9:45 since I was using a 1 minute delay between cycle checks starting at 9:30am) based on checking highly traded stocks apple, google, twitter, facebook and lyft. So there is a 1 minute delay between the API and the app and a 15 minute delay for the start of the trading day.
