### ISSUE TITLE
place_limit_buy_order working for equities but not options

### ISSUE THREAD

**Issue by edPratt** [robinhood-unofficial/Robinhood#179]
Regular Equity Buy:
```
In [92]: my_trader.place_limit_buy_order(
    ...:     instrument_URL=aapl['url'],
    ...:     symbol='AAPL',
    ...:     time_in_force='GFD',
    ...:     price=float(10.00),
    ...:     quantity=1
    ...: )
{
  'account': 'https://api.robinhood.com/accounts/**redacted**/',
  'instrument': 'https://api.robinhood.com/instruments/450dfc6d-5510-4d40-abfb-f633b7d9be3e/',
  'symbol': 'AAPL', 
  'type': 'limit', 
  'time_in_force': 'gfd', 
  'trigger': 'immediate', 
  'price': 10.0, 
  'quantity': 1, 
  'side': 'buy'
}

Out[92]: <Response [201]>
```

Option Buy:
```
In [93]: my_trader.place_limit_buy_order(
    ...:     instrument_URL=option['url'],
    ...:     symbol=option['chain_symbol'],
    ...:     time_in_force='GFD',
    ...:     price=float(0.01),
    ...:     quantity=1
    ...: )
{
  'account': 'https://api.robinhood.com/accounts/**redacted**/', 
  'instrument': 'https://api.robinhood.com/options/instruments/da36324b-82b6-4cf0-8090-b8c42a37cc89/', 
  'symbol': 'AAPL',   
  'type': 'limit', 
  'time_in_force': 'gfd',  
  'trigger': 'immediate', 
  'price': 0.01, 
  'quantity': 1, 
  'side': 'buy'
}
400 Client Error: Bad Request for url: https://api.robinhood.com/orders/
```

Note: I have read through [this](https://github.com/Jamonek/Robinhood/issues/28) issue and verified that I have the changes that appear to have solved that problem. This seems to be something else, especially since placing an equity order works, but an options order doesn't.

**Comment by beards1120** [comment]
I think placing option orders uses a different endpoint, and would therefore need some larger updates and/or a entirely different function

https://api.robinhood.com/options/orders/
Vs
https://api.robinhood.com/orders/

I would love to see some of this functionality worked into this repo though.

**Comment by viaConBodhi** [comment]
I'm using the fast_arrow package as it is geared to options
https://github.com/westonplatter/fast_arrow
Has not been updated with the recent MFA stuff but has been working for what I need with slight modifications. I login to RH using my updated fast_arrow package and updated the jamoek packaged login to pass the credentials so I can access the jamoek functions as fast_arrow does not have much in the way of stocks and portfolio. Code  is below. 

`(from fast arrow)
client = Client(username=, password=)

(from jamoek)
my_trader = Robinhood()
logged_in = my_trader.login(client)



    def login(self,*args):
        for i in args:
            testing = i.access_token
            username = i.username
            password = i.password
            device_token = i.device_token
            auth_token = i.access_token
            refresh_token = i.refresh_token
        
        self.auth_token = auth_token
        self.refresh_token = refresh_token
        self.headers['Authorization'] = 'Bearer ' + auth_token`

**Comment by beards1120** [comment]
Has anyone been able to successfully integrate the options orders? I keep getting a 400 error on the post.
