### ISSUE TITLE
LOGIN issue

### ISSUE THREAD

**Issue by cosmo86** [robinhood-unofficial/Robinhood#183]

**Comment by aseylys** [comment]
They changed their API. The login post now has the following parameters:
`{"grant_type":"password","scope":"internal","client_id":"c82SH0WZOsabOXGP2sxqcj34FxkvfnWRZBKlBjFS","expires_in":86400,"device_token": [YOUR DEVICE TOKEN],"username":[YOUR USERNAME],"password":[YOUR PASSWORD]}`

What you have to do is login to Robinhood on your computer (I use Firefox so this will be tailored to that).
-Go to Robinhood.com (logout if already logged in)
-Right click > Inspect Element
-Go to the Network tab (3rd from the right)
-Enter "token" in the input line at the top where it says "Filter URLs"
-With the network monitor-er open, login to Robinhood
-You'll see two new urls pop up that say "api.robinhood.com" and "/oauth2/token"
-Click the one that's not 0 bytes in size
-Go to "Params" tab on the right
There you will see all the new JSON parameters for your specific login.
-Now go into the source code for this specifically `Robinhood.py`
-Edit lines 105-110 with your newly acquired JSON

**Comment by mhaytmyr** [comment]
Thanks for tip, I was scratching my head to get access_token.

**Comment by NathanMaton** [comment]
Thanks for the tips, I also got this to work, is it possible we could make a PR to help others using this or is that device token something that changes frequently?

Here's what I found:
client_id: "c82SH0WZOsabOXGP2sxqcj34FxkvfnWRZBKlBjFS"
device_token: [YOUR DEVICE TOKEN]
expires_in: 86400
grant_type: "password"
password: [YOUR PASS]
scope: "internal"
username: [YOUR USERNAME]

**Comment by aseylys** [comment]
@NathanMaton I don't think so. A device token is uniquely generated based on the combination of the App (Robinhood) and the device that is accessing it. 

I'll play around with it a little more this weekend and get back to you.

**Comment by roddds** [comment]
@aseylys are you sure it's not a simple random uuid?

**Comment by psingapati** [comment]
I am still facing the same error , after changing payload with required JSON params
Any other suggestion to check.

**Comment by psingapati** [comment]
@aseylys  , @NathanMaton 
I am still facing the same error , after changing payload with required JSON params

payload = {
            'password': password,
            'username': self.username,
            'grant_type': 'password',
            'client_id': self.client_id,
            'device_token': self.device_token,
            'expires_in': 86400,
            'scope': 'internal'
        }
I have taken device token from chrome browser and defined like client_id

Can you please suggest

**Comment by osum4est** [comment]
@psingapati Make sure you log in successfully on the browser using that device token. I had to enter an SMS verification and log in on the browser before the api worked.

**Comment by psingapati** [comment]
@osum4est Thanks for the reply.  I am able to login successfully on chrome browser. But with the API I am getting error.

**Comment by osum4est** [comment]
@psingapati Make sure you have 2FA turned off in robinhood settings. If that doesn't work then I'm not sure

**Comment by psingapati** [comment]
@osum4est I reviewed the 2FA. It is off.
still did not work 

Then I realised that I am change the code in the git hub path but not reinstalling the package.
I did "pip install ." It worked :)

Thanks a lot

Thanks @aseylys  @NathanMaton

**Comment by NathanMaton** [comment]
@aseylys sounds like you may be right on the device id.

**Comment by GoldenEye22** [comment]
Hey do you realize the login issue was solved here #176 by @ammazie. @Jamonek needs to merge his fixes by reference the code in #176

**Comment by DuhaTech** [comment]
does anyone know how to get my qr code as per aamazie's update? I turn on 2FA from my app(android) and select "Google Authenticator", the next is Robinhood giving me a 16-character key and ask me to copy it into my google authentication app. i really don't see the "Can't Scan It?" option as described.  thanks.

**Comment by ausername2** [comment]
> Thanks for the tips, I also got this to work (on chrome, you'll see a tick box next to the word 'token/' and if you tick that off then the info shows up to the right.
> 
> Is it possible we could make a PR to help others using this or is that device token something that changes frequently? I'm not sure I know where that device token value comes from or if it changes. I also then used all of that to get an access token rather than just copying and pasting it from the network request.
> 
> Here's what I found:
> client_id: "c82SH0WZOsabOXGP2sxqcj34FxkvfnWRZBKlBjFS"
> device_token: [YOUR DEVICE TOKEN]
> expires_in: 86400
> grant_type: "password"
> password: [YOUR PASS]
> scope: "internal"
> username: [YOUR USERNAME]

Where the heck is this hard coded client_id coming from ?
