### ISSUE TITLE
After-Hours Orders Not Being Filled

### ISSUE THREAD

**Issue by ecmulli** [robinhood-unofficial/Robinhood#187]
I am trying to place an after-hours order for stock 'LC' using the following code:
```
stock = user.instruments('LC')[0]
user.place_market_buy_order(stock["url"],  'LC' ,"GFD", 1)
```
The lines work fine in normal trade hours but after-hours I see them as "Queued" in the application. I would dismiss this just as being a market issue, no one is willing to sell but the exact same market order works from the application itself. I even tried to place a limit order `  user.place_limit_buy_order(stock["url"], 'LC' ,"GFD",2.98, 1)
` 
 at the same price the order executed at within the application but that didn't work either. 

Thoughts? Is it an api issue or is their a fundamental difference in the order the api puts in versus the application?

**Comment by kuhner** [comment]
I don't believe there is any functionality in this repository for placing after market orders. Everything uses regular market hours. I was actually about to add a issue to see if this feature could be added. It seems like it may just be adding an extra parameter to the requests to set after hours to true.

**Comment by ecmulli** [comment]
What do the api endpoints look like? I don’t think there should be a distinction the types of orders during market hours and after. 

I think I’d extend this issue to in-market hours too. I have found sometimes that market buys/sells will show as pending when placed through the API but the same order placed in the app fills immediately.

**Comment by kuhner** [comment]
Just tested this out. The order has been queued and when the order status is retrieved the 'extended_hours' value is true. 
Code added:
payload['extended_hours'] = True
to line 1357 of Robinhood.py

More should be done to parameterize this in other functions but this should tell us if its do-able.

**Comment by thehaitiancoder** [comment]
Does this still work in May 2020? I have been trying to put an after-hours order but it's not working
