### ISSUE TITLE
order_history() truncated

### ISSUE THREAD

**Issue by kohlkopf** [robinhood-unofficial/Robinhood#189]
I use Robinhood mainly for options trading. `order_history()` doesn't seems to return my options trading history. Is this the wrong function to use? I would expect all order history to be returned.

Thanks for the hard work!

**Comment by viaConBodhi** [comment]
@kohlkopf checkout the fast_arrow package as this has been a good resource for options. I only do a few small things with options and even with this package I still need to compile from a few different APIs to get what I need for reporting. I think fast_arrow is still under development to have the new MFA update but you should be able to add the endpoints and methods from fast_arrow and pass the keys from Jamonek auth method to get it working. I'm doing the same thing in reverse, authenticating with a modified fast_arrow and passing the keys to a modified Jamonek.
