### ISSUE TITLE
Any support for option?

### ISSUE THREAD

**Issue by 1a1a11a** [robinhood-unofficial/Robinhood#190]
Any support for option?

**Comment by viaConBodhi** [comment]
I'm assuming you mean methods for options trading...Checkout the Fast_Arrow library. It has several methods not contained in Jamonek that I've found handy for working with options. With a little modification you can modify the auth/login methods for either library so you can use the keys you login with one package for both packages. I use both as each have their own particular strengths.

**Comment by 1a1a11a** [comment]
Thank you!

**Comment by westonplatter** [comment]
@viaConBodhi thanks for the shoutout. 

@1a1a11a just to chime in ... https://github.com/westonplatter/fast_arrow was built specifically for options trading. We just did an overhaul on authentication and released 1.0.0. Please open an issue if there missing features or you run into bugs.

**Comment by 1a1a11a** [comment]
Thank you @westonplatter!
