### ISSUE TITLE
Where the heck is hard coded client_id coming from?

### ISSUE THREAD

**Issue by ausername2** [robinhood-unofficial/Robinhood#191]
https://github.com/Jamonek/Robinhood/blob/95ed2aa7fdeace912595f87e2489dbe87dfe75fb/Robinhood/Robinhood.py#L50

Where the heck is this hard coded client_id originating from  / what is it?

**Comment by sagivo** [comment]
magic

**Comment by sanko** [comment]
Stolen from the official clients. This is why things got ugly with Robinhood.
