### ISSUE TITLE
Error 401 Client Error

### ISSUE THREAD

**Issue by eilin75** [robinhood-unofficial/Robinhood#194]
I have getting this error for the past week.  has anybody seen this?

  raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.robinhood.com/accounts/

**Comment by hkscriber** [comment]
Yeah, I'm seeing the same thing.

**Comment by TBrannan** [comment]
I'm getting this as well
```.HTTPError: 401 Client Error: Unauthorized for url: https://api.robinhood.com/quotes/AAPL/```

**Comment by juelich23** [comment]
Looks like I'm getting the same issues as well, even tried using 2FA login. No luck.

**Comment by viaConBodhi** [comment]
Just tested using 
final = 'https://api.robinhood.com/accounts/'
test = my_trader.session.get(final).json()
and I was able to get a return. I'm using 2FA with a modified version of this package and another, FastArrow...but both are basically using similar logic to retrieve the token(s) so I'm wondering if it's something in the way you all are authenticating and/or passing the token back when needed. Are you getting errors when establishing authentication or only after when trying to use?

**Comment by UreshiiUreshii** [comment]
Yeah, I am also getting this error.

`Traceback (most recent call last):
  File "C:\Users\Master\Anaconda3\envs\tensorflow\lib\site-packages\Robinhood\Robinhood.py", line 354, in quote_data
    req.raise_for_status()
  File "C:\Users\Master\Anaconda3\envs\tensorflow\lib\site-packages\requests\models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.robinhood.com/quotes/NRZ/`
