### ISSUE TITLE
Login error seems to be back.

### ISSUE THREAD

**Issue by rawspinach** [robinhood-unofficial/Robinhood#196]
I installed Python 3.8, got all the necessary libraries, and got a fresh install of this repository. Then I try to run example.py and I get:

```
requests.exception.hTTPError: 400 Client Error: Bad request for url: https://api.robinhood.com/oauth2/token/

During handling of the above exception another exception occurred:

raise RH_exception.LoginFailed()
```

I saw another user say that (months ago) Robinhood updated their payload requirements but I have seem to met them?

```
payload = {
  'client_id': MYCLIENTID,
  'device_token': MYDEVICETOKEN,
  'expires_in': 86400,
  'grant_type': 'password',
  'scope': 'internal',
  'password': MYPASSWORD,
  'username': MYUSERNAME
}
```

Still get a login failed... Used to work!!!

**Comment by qualiaMachine** [comment]
Same problem here

**Comment by zacharytyhacz** [comment]
Any solution? Is something MFA related? Or did it just start 'suddenly' working?

**Comment by machuiwen** [comment]
Using the parameters above I was able to login. Probably you need to login on web first to get a valid token?

**Comment by FergusClare** [comment]
I'm having the same problem.  2FA is on and I have a valid token.  I keep getting a 400 Client Error notification after entering my 2FA code.  I'm able to login via the web based application (desktop) and mobile app without incident.

Here's the error I get:
```Python
>>> from Robinhood import Robinhood
>>> mytrader=Robinhood()
>>> logged_in=mytrader.login(username="xxxx", password="xxxx")
MFA: xxxxxx
Traceback (most recent call last):
  File "/Users/Fergus/Dropbox/VINST/software/Robinhood/Robinhood/Robinhood.py", line 123, in login
    res.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/requests/models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.robinhood.com/oauth2/token/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Fergus/Dropbox/VINST/software/Robinhood/Robinhood/Robinhood.py", line 130, in login
    return self.login(username,password,mfa_code)
  File "/Users/Fergus/Dropbox/VINST/software/Robinhood/Robinhood/Robinhood.py", line 126, in login
    raise RH_exception.LoginFailed()
Robinhood.exceptions.LoginFailed
```
I've updated the Robinhood source file to include the access_token, expires_in, token_type, scope, refresh_token, challenge_type, and device_id and saved this file before navigating back to the Robinhood directory to reinstall the source file via "pip3 install ." to no avail.  Here is what my Robinhood payload looks like now:
```Python
        payload = {
            'password': password,
            'username': self.username,
            'grant_type': 'password',
            'client_id': self.client_id,
            "access_token": "xxxx",
            "expires_in": xxxx,
            "token_type": "Bearer",
            "scope": "internal",
            "refresh_token": "xxxx",
            'challenge_type': 'sms',
            "device_id": "xxxx"
        }
```
Any help would be much appreciated.

**Comment by securient** [comment]
It appears that the login requires device_token. I tried to push my changes by creating a PR but received an authorization error.

In order for you to make it work, you could use uuid library to generate a device token in Robinhood.py file. 

```import uuid

class Robinhood:

  def login(self,
                username,
                password,
                mfa_code=None):

    devicetoken = uuid.uuid1()

    self.username = username
            payload = {
              'password': password,
              'username': self.username,
              'grant_type': 'password',
              'client_id': self.client_id,
              'device_token': devicetoken
            }

```

**Comment by qualiaMachine** [comment]
Thanks for the suggestion. Unfortunately, this fix does not appear to work on my end (same error as others report). I have already verified I can login to RH via web and mobile.

**Comment by FergusClare** [comment]
> I'm having the same problem. This appears to be related to issues #176 #177 #183. 2FA is on and I have a valid token. I keep getting a 400 Client Error notification after entering my 2FA code. I'm able to login via the web based application (desktop) and mobile app without incident (Version 2019.51.37).
> 
> Here's the error I get:
> 
> ```python
> >>> from Robinhood import Robinhood
> >>> mytrader=Robinhood()
> >>> logged_in=mytrader.login(username="xxxx", password="xxxx")
> MFA: xxxxxx
> Traceback (most recent call last):
>   File "/Users/Fergus/software/Robinhood/Robinhood/Robinhood.py", line 123, in login
>     res.raise_for_status()
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/requests/models.py", line 909, in raise_for_status
>     raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.robinhood.com/oauth2/token/
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Users/Fergus/software/Robinhood/Robinhood/Robinhood.py", line 130, in login
>     return self.login(username,password,mfa_code)
>   File "/Users/Fergus/software/Robinhood/Robinhood/Robinhood.py", line 126, in login
>     raise RH_exception.LoginFailed()
> Robinhood.exceptions.LoginFailed
> ```
> 
> I've updated the Robinhood source file to include the access_token, expires_in, token_type, scope, refresh_token, challenge_type, and device_id and saved this file before navigating back to the Robinhood directory to reinstall the source file via "pip3 install ." to no avail. Here is what my Robinhood payload looks like now:
> 
> ```python
>         payload = {
>             'password': password,
>             'username': self.username,
>             'grant_type': 'password',
>             'client_id': self.client_id,
>             "access_token": "xxxx",
>             "expires_in": xxxx,
>             "token_type": "Bearer",
>             "scope": "internal",
>             "refresh_token": "xxxx",
>             'challenge_type': 'sms',
>             "device_id": "xxxx"
>         }
> ```
> 
> Any help would be much appreciated.

The note by @securient helped solve my problem.  I changed the "device_id" to "device_token" in my payload, removed MFA and was then able to login without issue.

**Comment by securient** [comment]
@qualiaMachine, are you still getting the same error? Take a look at this PR https://github.com/Jamonek/Robinhood/pull/198/files and see if you have made the same changes in your code.

**Comment by peweetheman** [comment]
I made those changes, still getting the error

**Comment by tipu** [comment]
I swapped out the `device_id` in the login payload with one that was sent using the login on the browser and that worked. Generating a random uid per the PR posted by @securient did not work.

**Comment by securient** [comment]
@peweetheman @tipu I think I know why it's not working. with uuid.uuid1(), it is actually sending an UUID object and not an actual UUID hex string. try `devicetoken = uuid.uuid1().hex` and it should work.

**Comment by alake16** [comment]
Working with @securient changes outlined above!

**Comment by alake16** [comment]
@securient's solution works when MFA is enabled in the account. It does not fix the issue when MFA is NOT enabled.

**Comment by Outlaw782** [comment]
Was there ever a solution to the above? I am a new user trying to log in and getting this error myself.

**Comment by Outlaw782** [comment]
@alake16 @securient @tipu

**Comment by diogobotelho** [comment]
Same here. Only works with MFA on and I have to type th 6-digit code. Any suggestions?

**Comment by zacharytyhacz** [comment]
@adithyabsk  Why is this closed?

**Comment by diogobotelho** [comment]
@zacharytyhacz yes, I don't know either. Is this resolved, please let us know.

**Comment by adithyabsk** [comment]
@zacharytyhacz @diogobotelho have you tried the project recently? Login works

**Comment by joshith** [comment]
hey @adithyabsk it seems there is some intermittent issue. Login works for me in my mac. but doesn't work in my linux (Centos) with same parameters. MFA enabled. getting HTTP error 400. Only difference AFAIK, in my mac its Python3.7 Linux 3.6. Any clue?
