### ISSUE TITLE
HTTPError: 400 When trying to create an order.

### ISSUE THREAD

**Issue by ggiv** [robinhood-unofficial/Robinhood#206]
Trying to create market or limit orders generates HTTPError 400 on my end. Does anyone have this type of problem? Maybe this is related to the recent outages..

**Comment by Jamonek** [comment]
Hey @ggiv, try attempting with the recent changes

**Comment by ggiv** [comment]
It worked!

**Comment by adithyabsk** [comment]
@ggiv great!
