### ISSUE TITLE
Grabbing 52 week high and 52 week low

### ISSUE THREAD

**Issue by hamt3ch** [robinhood-unofficial/Robinhood#212]
Is is possible to grab the 52 week high and low for a given stock. 
For example:
```
rh.quote_info('AAPL')['52wk_high']
>> '334.34'
```

**Comment by GoldenEye22** [comment]
yes

**Comment by GoldenEye22** [comment]
fundamentals  = trader.fundamentals('DIS')
low = fundamentals['high_52_weeks']
high = fundamentals['low_52_weeks']

**Comment by adithyabsk** [comment]
I'm going to consider this issue closed.
