### ISSUE TITLE
setup.py missing?

### ISSUE THREAD

**Issue by jtngangani** [robinhood-unofficial/Robinhood#213]
Hi 

I clone the directory but cant find setup.py under root. I see setup.cfg though. How do I work with that? Is ReadMe updated?

**Comment by adithyabsk** [comment]
just install it from pypi. I need to update the README.
```
pip install pyrh
```

**Comment by adithyabsk** [comment]
though, if you're curious, it uses pyproject.toml, the latest PEP standard and poetry to build the project so you can still follow the instructions to pip install . as long as your pip version is greater than 19.1

**Comment by jtngangani** [comment]
I did successfully install pyrh (pip install pyrh) but when I run the
jupyter notebook, it says "module pyrh not found". I think I can probably
run using standard python

**Comment by adithyabsk** [comment]
@jtngangani That's likely because you don't have the package installed in the "python environment" the jupyter notebook is using. Are you using conda or something to set up jupyter? In the notebook, type `!pip freeze` to check to see if the package is properly installed. If note go ahead and install it using `!pip install pyrh`

**Comment by jtngangani** [comment]
I did
-  sudo apt get install jupyter-notebook
- jupyter-notebook &

and opened the example.py. I dont know what python environment its using.

**Comment by adithyabsk** [comment]
@jtngangani yep, and in a cell all you need to do is run the above `!pip install pyrh`. Let me know if that works. The preferred way to set up jupyter (afaik) is to install it locally using `pip install jupyter` in a virtualenv set up to manage notebooks. (or use conda)

**Comment by jtngangani** [comment]
Ok.
- Created virtualenv.
- pip install pyrh
- pip install jupyter
- jupyter notebook

Browsed to example.ipynb and ran it. Same error -
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-100bf0f90b65> in <module>()
----> 1 from pyrh import Robinhood
      2 from pprint import pprint

ModuleNotFoundError: No module named 'pyrh'

**Comment by adithyabsk** [comment]
Did you remember to activate the virtualenv?
```bash
$ python --version # python 3.3+ for venv functionality
Python 3.7.6
$ python -m venv pyrh_env
$ source pyrh_env/bin/activate
(pyrh_env) $ pip install pyrh
(pyrh_env) $ pip install jupyter
(pyrh_env) $ jupyter notebook

**Comment by jtngangani** [comment]
Thanks Aditya. That worked. I was actually pip installing outside venv. :(

Qs:
1 - What is the GEV0 symbol that you have buy/sell test in your notebook?
2 - I wish to get my entire portfolio and transactions from robinhood.
where can I find the API information for that?

Jatin

**Comment by jtngangani** [comment]
Nvm. I am exploring the robinhood.py

**Comment by adithyabsk** [comment]
@jtngangani glad to hear it, marking this issue as closed for now.
