### ISSUE TITLE
get_quote function not returning quote

### ISSUE THREAD

**Issue by jonl1096** [robinhood-unofficial/Robinhood#26]
Currently, the get_quote function returns the symbol of the stock instead of the quote, and is implemented like so:

```
def get_quote(self, stock=''):
        """wrapper for quote_data"""
        data = self.quote_data(stock)
        return data["symbol"]
```

I believe instead of returning "symbol" attribute  for `data`, it should be returning the "last_trade_price" attribute?

**Comment by Jamonek** [comment]
Thoughts of others on this?

**Comment by lockefox** [comment]
`/quote` has both a `last_trade_price` and a `last_extended_hours_trade_price`.  And splitting on/off hours requires up to 2 more pulls (`/fundamental`->`/market_hours`, esp for holiday coverage).

I agree `get_quote()` should probably not just echo `symbol`

**Comment by jasonleehodges** [comment]
@jonl1096 would the print_quote() method resolve this issue?

**Comment by m-deck** [comment]
I feel like print_quote() doesn't resolve this - IMO get_quote() should return the quote as a float.
