### ISSUE TITLE
Methods for volume and avg volume

### ISSUE THREAD

**Issue by KenRapkin** [robinhood-unofficial/Robinhood#45]
Hi,

By any chance, will there be methods for volume and avg volume in the near future? If I missed it in the code, please point out the terminology if different. 

Thanks!

**Comment by TomFaulkner** [comment]
@KenRapkin I don't believe Robinhood provides that information, though it would be nice to have. As far as I know the primary, perhaps only, API documentation is here:
https://github.com/sanko/Robinhood

I don't see anything about volume there. It might be possible to add volume information from another source, such as Google Finance, Yahoo Finance, or others, though that would probably be outside of the scope of this library.
