### ISSUE TITLE
Automated Unit Test with Travis CI

### ISSUE THREAD

**Issue by mannyrivera2010** [robinhood-unofficial/Robinhood#50]
Add PR to integrate Travis CI to automate unit testing

**Comment by lockefox** [comment]
I was thinking of doing this, but I'm not sure what the best plan is for protecting passwords.

Since travis plans are run automatically on PR's, it's possible to do an environment dump to expose passwords, and Robinhood doesn't provide a sandbox environment

**Comment by TomFaulkner** [comment]
Many of the API calls can be done without being logged in, those could be tested against the live server.Of course, proper testing with Mock really needs done as well.

**Comment by lockefox** [comment]
I agree with @TomFaulkner that much of the responses can be mocked, but would like to put a little attention toward schema-checking live responses.  

Robinhood has been good so far with keeping keys consistent, but they are regularly adding keys to feeds.

**Comment by Jamonek** [comment]
Reviewing Travis CI. I'll touch back on this
