### ISSUE TITLE
How do I see what stocks I currently own?

### ISSUE THREAD

**Issue by Njreardo** [robinhood-unofficial/Robinhood#61]
I don't want to be guessing at what stocks I own and which ones I do not. Is there a way that I can enumerate my owned stocks? 

Ex. trade.mystocks()
['AAPL', 'MYSE']

**Comment by bdowling** [comment]
You can use securities_owned() to get your current list of securities.

```python
   import json
    curpos = rh.securities_owned()
    for position in curpos['results']:
        print("position", json.dumps(position, indent=3))
```

**Comment by vargasa** [comment]
Define your `trader` sign in and run:
```
dsecowned = trader.securities_owned()['results']

for position in dsecowned:
    id = position['instrument'].split('/')[4]
    if position['quantity'] > 0 :
        trader.instrument(id)['symbol']
        position['quantity']
```

**Comment by Njreardo** [comment]
Vargasa I know you're on to something good but I can't get your code to work. Can you show the functions that you are using? The code trips up on me when I get to "trader.instrument(id)['symbol']" and says that res['results'] is not there or something. Error.
