### ISSUE TITLE
Tests Broken + Travis-CI 

### ISSUE THREAD

**Issue by lockefox** [robinhood-unofficial/Robinhood#64]
Looks like the test-pass is mostly red and hasn't been run against recent changes.  Tests will need to be updated to be green and we should add Travis-CI integration to keep future PR's honest.

**Comment by Jamonek** [comment]
I'm setting up CircleCI. Do you believe Travis-CI is the better option?

**Comment by lockefox** [comment]
Travis is just default.  Any CI is ok.

My concern is that 50% of the coverage requires live account keys.  These can be masked in Travis, but will automatically run against any PR.  This means someone could print the env vars in py and get creds.  Or add cheeky code to a test pass and execute real orders.

I've been looking at pytest.mark to mask away auth tests, and mocking for a full pass... But I'd still like live-schema checks to know when RH has changed something

**Comment by lockefox** [comment]
Picking through the options (codeship, travis, circle).  All the public versions seem to be the same deal: setup runs with public views, and gets pricy fast.

Travis is ubiquitous, and I'd be happy to formulate a PR to at least get un-authed stuff tested.  I'd prefer Travis/CircleCI over Codeship b/c the testplan would at least be in the repo.  I'm also digging into options on gitlab, but I'm not sure what the sync options look like between github/gitlab.

**Comment by westonplatter** [comment]
@lockefox any update on this?

**Comment by Jamonek** [comment]
@westonplatter I'm setting CI using CircleCI

**Comment by westonplatter** [comment]
@Jamonek score.

**Comment by westonplatter** [comment]
@Jamonek out of curiosity, how are you keeping the username/password secret? Is the Circle CI repo public?
