### ISSUE TITLE
Orders not being filled?

### ISSUE THREAD

**Issue by nlowell11** [robinhood-unofficial/Robinhood#65]
I am trying to get up and running with this code; apologies if this is an error on my end and not an issue with the codebase.

I tried programmatically ordering one share of a small company a couple minutes after market open today. The order appeared to be successfully placed and I could view it in the app. However, the order was never filled during the day. At the end of the day, 4:00, it appeared to be automatically cancelled. I tried ordering the same shares in-app during the day and the orders were filled successfully.

Is there anything I could be doing wrong to cause the order to show up in-app but not be filled? Thank you.

**Comment by sirusss** [comment]
@nlowell11 can you provide more information with how you're placing the order via your script? A code snippet and return response would be helpful.

**Comment by bdowling** [comment]
@nlowell11 If the order was visible in the app, perhaps this is simply a matter of the market moving away from your order price quickly? Did the stock gap?  RH automatically wraps "market" orders in a limit order with a 5% buffer.

**Comment by nlowell11** [comment]
Thank you for the help so far.
 @sirusss I do not have my code in front of me right now, but it is basically a very simple modification of the example code, something like:
my_trader.place_buy_order(stock_instrument,1)
where stock_instrument is "AMD". I will post the exact code later today. I will also grab the response and post it as well.
@bdowling The price moved less than 5% at market open, so I do not think this was caused by a stock gap.

**Comment by awoodman** [comment]
Hi all, I noticed something similar to @nlowell11 where I execute the following code after hours and I see the orders in the app as 'queued'. The next day, I see the items in the app as 'placed'. The price definitely did not fluctuate even close to 5%. If this is a market order, why isn't it placed right at market open?

```python
from Robinhood import Robinhood

my_trader = Robinhood();

my_trader.login(username="YOUR_USERNAME", password="YOUR_PASSWORD")

stock_instrument = my_trader.instruments("ZNGA")[0]

buy_order = my_trader.place_buy_order(stock_instrument, 1)
```

**Comment by nlowell11** [comment]
@sirusss 

My code:

```
my_trader = Robinhood()
my_trader.login(username="XXXXXXXXX", password="XXXXXXXXX")
stock_instrument = my_trader.instruments("AMD")[0]
response = my_trader.place_buy_order(stock_instrument, 1)
```

I've tried to grab relevant parts of the response, but this is only from an after-hours test, so I'm not sure if market hours would be the same (will check tomorrow):
response.ok: True
response.status_code: 201

**Comment by bdowling** [comment]
@nlowell11  I'm sorry, I forgot about this issue, I've been working with my own branches for so long.

The current HEAD I believe is still placing market orders with a bid_price of 0.  This obviously would not work.  

When submitting an order to Robinhood, the client needs to still provide the current bid_price to the API.  My branch in https://github.com/Jamonek/Robinhood/pull/62 and subsequent https://github.com/bdowling/Robinhood/tree/fix_place_order_and_waymore_module_rename includes the current bid_price in the order.

**Comment by nlowell11** [comment]
Thanks @bdowling. To be honest I am still a bit of a novice with git/github, I had also totally forgotten I was using an older version of this code. 

I will check out your branch.

As an aside, do you know of a way I could test this while the market is closed? I run the RH code from my home setup, and I am away from it during workdays. I imagine an example of a request you know to be successful would be very helpful to me.

**Comment by timetoadd** [comment]
Is there an enhancement for this issue?

**Comment by justin-pierce** [comment]
Just had this happen to me -- order was placed, but didn't get a fill. The stock I tried to buy was less than $1 so I thought that might be part of it, but doing the same thing through the app itself worked fine.

**Comment by GregP83** [comment]
Had the same for buy and sell market. All looks good - order is also in RH app - but not getting filled (status 'pending'). I switched to using limit orders and it works fine.
