### ISSUE TITLE
Installation 

### ISSUE THREAD

**Issue by flare9x** [robinhood-unofficial/Robinhood#66]
Hi 

I downloaded all .py files. I obtain this error when I try and run Robinhood.py 

C:\Users\flare9x\Anaconda3\envs\first.coint\python.exe C:/Robinhood/Robinhood-master/Robinhood-master/Robinhood/Robinhood.py
Traceback (most recent call last):
  File "C:/Robinhood/Robinhood-master/Robinhood-master/Robinhood/Robinhood.py", line 19, in <module>
    from . import exceptions as RH_exception
ImportError: cannot import name 'exceptions'

Process finished with exit code 1

This line seems to be the error:

**Comment by flare9x** [comment]
changed:

#Application-specific imports
import exceptions as RH_exception

No problems now and I can request quotes etc.. very cool, thanks!

**Comment by Jamonek** [comment]
Hey Andrew,

What version of Python are you using?

Best,

Jamone

**Comment by flare9x** [comment]
Hi Jamone

I am using python 3.6.3

I didnt install it with pip install .

I now got it working:

I changed to:

#Application-specific imports
> import exceptions as RH_exception

I just tested it out and I was able to send and order to RH!! Very cool.

Is there a way to obtain my open positions? Or in example.py, is that all
the functionality there is right now?
Also - this API is for sending orders only right and not a solution for
streaming live market data... and running algos in real time on RH data?

This is very cool though!! I have some daily strategies I have coded in R
and I can cann python scripts in R too, so when my conditions met I can
call a buy.py or sell.py. But for checking which positions I have, i wanted
to do that with you API.

Thanks!

Andrew
