### ISSUE TITLE
Save Authentication Token

### ISSUE THREAD

**Issue by TomFaulkner** [robinhood-unofficial/Robinhood#71]
Authentication token should be easily saved and should be the preferred method of logging in, at least as the default. This means users don't need to save their usernames and passwords and don't need to enter them with each run.

**Comment by Jamonek** [comment]
I believe that’s outside the scope of the project. Open to others opinion

**Comment by TomFaulkner** [comment]
I think that is actually more in-scope than having getpass and asking users to enter credentials into a library. :)

I'm not suggesting adding saving the token for the user, rather just making it simple for the user to do, as it is should be preferred user/pass authentication, unless Robinhood is prone to changing the tokens, which I don't believe they are.

**Comment by lockefox** [comment]
The issue is it's not a once-per-session token.  I'm not sure the time scale, but tokens expire after a few minutes.

Adding token tracking is possible, but should also be paired with an `atexit` handler so users won't end up with floating sessions.  Also, testing vs time out could be a sticky testcase.

**Comment by TomFaulkner** [comment]
I'm fairly certain they don't expire anywhere near that quickly, when I was using this library I kept one for days. Though, to be fair, I haven't used it for some time.

**Comment by lockefox** [comment]
I have been experimenting with authenticated feeds in the last week or so, and I don't think a token stays alive for longer than 10mins.

Refreshing is possible with a [try-auth-retry loop](https://github.com/lockefox/pyRobinhood/blob/master/pyrobinhood/crawler.py#L87) but having user/PW is going to be a better set of creds than just Token.  Though I haven't played with their oAuth connection, which might have more persistent keys.

**Comment by TomFaulkner** [comment]
Updated above. My token is months old and still works.

**Comment by justin-pierce** [comment]
After logging in, will that session ever expire? Is there a way to check if I'm still logged in?

**Comment by jasonleehodges** [comment]
From my findings the basic authorization returns a token that either never expires or has a really long life. If you take that token and convert it to an oauth token, that has a more normal expiration life (like an hour or something). You don't need to check if you are logged in per se, you just need to have that token available to feed the requests that the library calls to the endpoints. When you construct a new instance of Robinhood() it creates a session which will not terminate unless you either manually terminate it in your script or stop your script all together. When you start your script again and need to re-instantiate the Robinhood() class you'll need to call one of the login methods again. But if you stored your token somewhere locally you could just do something like this:

```
from Robinhood import Robinhood

rb = Robinhood()
rb.auth_token = {locally saved token somewhere}
rb.headers['Authorization'] = 'Token ' + rb.auth_token
```

**Comment by metrodraftingdesign** [comment]
Trying to pass a token to RH but it is giving me an 'Invalid Token' error...I try both the access and refresh token but neither works... Here is the line

MyRequest.SetRequestHeader "Authorization", "Token XXXXXRrxL2xZqRD8pHaC702DUqj"

Any help is appreciated!
