### ISSUE TITLE
No module named bsddb185

### ISSUE THREAD

**Issue by jerry1091** [robinhood-unofficial/Robinhood#75]
I'm having issues running the trade_history_downloader.py script in Ubuntu.
It's working fine in Mac OS but Ubuntu fails to populate the instrument.db (oddly on Mac OS it creates the file as 'instrument.db.db').
The error is 
  File "/usr/lib/python2.7/bsddb/__init__.py", line 270, in <lambda>
    return _DeadlockWrap(lambda: self.db[key])  # self.db[key]
TypeError: String or Integer object expected for key, unicode found

If I use the instrument.db (renamed to remove the extra .db) file from Mac I get this error:
  File "trade_history_downloader.py", line 51, in <module>
    instruments_db = shelve.open('instruments2.db')
  File "/usr/lib/python2.7/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/usr/lib/python2.7/shelve.py", line 227, in __init__
    Shelf.__init__(self, anydbm.open(filename, flag), protocol, writeback)
  File "/usr/lib/python2.7/anydbm.py", line 84, in open
    mod = __import__(result)
ImportError: No module named bsddb185

This is running in virtualenv 
Python 2.7.12

pip list :
certifi (2018.1.18)
chardet (3.0.4)
enum (0.4.6)
idna (2.6)
pip (9.0.1)
requests (2.18.4)
Robinhood (1.0.1)
setuptools (38.5.1)
six (1.11.0)
urllib3 (1.22)
wheel (0.30.0)

**Comment by jerry1091** [comment]
I've tested on a fresh install on CentOS7 with the same results.

**Comment by jerry1091** [comment]
$ python trade_history_downloader.py                                                                                                                                                                         
60 order fetched                                                                                                                                                                                                                  
Traceback (most recent call last):                                                                                                                                                                                                
  File "trade_history_downloader.py", line 52, in <module>                                                                                                                                                                        
    orders = [order_item_info(order, rb, instruments_db) for order in past_orders]
  File "trade_history_downloader.py", line 23, in order_item_info
    symbol = get_symbol_from_instrument_url(rb_client, order['instrument'], db)
  File "trade_history_downloader.py", line 9, in get_symbol_from_instrument_url
    if url in db:
  File "/usr/lib64/python2.7/shelve.py", line 110, in __contains__
    return key in self.dict
  File "/usr/lib64/python2.7/_abcoll.py", line 369, in __contains__
    self[key]
  File "/usr/lib64/python2.7/bsddb/__init__.py", line 270, in __getitem__
    return _DeadlockWrap(lambda: self.db[key])  # self.db[key]
  File "/usr/lib64/python2.7/bsddb/dbutils.py", line 68, in DeadlockWrap
    return function(*_args, **_kwargs)
  File "/usr/lib64/python2.7/bsddb/__init__.py", line 270, in <lambda>
    return _DeadlockWrap(lambda: self.db[key])  # self.db[key]
TypeError: String or Integer object expected for key, unicode found

**Comment by jerry1091** [comment]
Fixed....

Changed :
`def get_symbol_from_instrument_url(rb_client, url, db):
    instrument = {}
    if url in db:
        instrument = db[url]
    else:
        db[url] = fetch_json_by_url(rb_client, url)
        instrument = db[url]
    return instrument['symbol']
`
to 

`def get_symbol_from_instrument_url(rb_client, url, db):
    instrument = {}
    url = str(url)
    if url in db:
        instrument = db[url]
    else:
        db[url] = fetch_json_by_url(rb_client, url)
        instrument = db[url]
    return instrument['symbol']
`

**Comment by secureray** [comment]
Using strings to look at the repo.db file shows there is probably a lot that you would want pre-defined in terms of tests, etc.

Perhaps what my Ubunt 18.04 system needs is to be able to access the db file using later BSD libraries.

  apt list --installed | grep python | grep bsd
  WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
  python-bsddb3/bionic,now 6.1.0-1build4 amd64 [installed]

However, a python file with the first line as:

  import bsddb3

gives the message:
  Traceback (most recent call last):
    File "shelve_test_read_repo-1.py", line 1, in <module>
      import bsddb3
  ImportError: No module named bsddb3

I have also tried:

pip install bsddb3
Collecting bsddb3
  Downloading https://files.pythonhosted.org/packages/e9/fc/ebfbd4de236b493f9ece156f816c21df0ae87ccc22604c5f9b664efef1b9/bsddb3-6.2.6.tar.gz (239kB)
    100% |████████████████████████████████| 245kB 3.6MB/s
    Complete output from command python setup.py egg_info:
    Can't find a local Berkeley DB installation.
    (suggestion: try the --berkeley-db=/path/to/bsddb option)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-gtHl64/bsddb3/

and have tried:

pip install bsddb3 --berkeley-db=/usr/lib/python2.7/bsddb

Usage:
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: --berkeley-db
