### ISSUE TITLE
2FA Login

### ISSUE THREAD

**Issue by fxmeister** [robinhood-unofficial/Robinhood#77]
When trying to login with 2FA enabled,  I get the exception "#requires a second call to enable 2FA"

Is there an API sanctioned way to login with 2FA or is it not supported?

**Comment by lockefox** [comment]
Yes there is: https://github.com/sanko/Robinhood/blob/master/Authentication.md#logging-in

But it is difficult to implement inside this API b/c there needs to be a human on the other side to fill out the 2FA info to get the token
