### ISSUE TITLE
Collections (for-you)

### ISSUE THREAD

**Issue by kanendosei** [robinhood-unofficial/Robinhood#90]
Any idea how to call the https://robinhood.com/collections/for-you endpoint? There are some very good bits of information in there and calling it directly yields the error: `requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://robinhood.com/collections/for-you`

**Comment by mstrum** [comment]
Do you mean https://analytics.robinhood.com/instruments/tag/for-you ?  I haven't seen collections.

Here's an example of output from that API: https://github.com/mstrum/robinhood-python/blob/master/robinhood/RobinhoodClient.py#L872
