### ISSUE TITLE
Is there a way to check how much buying power I have?

### ISSUE THREAD

**Issue by Njreardo** [robinhood-unofficial/Robinhood#97]
My problem is as stated in the title. Is there any way I can check how much buying power I have?

**Comment by Njreardo** [comment]
I'm sorry I already asked this question and the thread was closed.

**Comment by jasonleehodges** [comment]
Does the closed thread [#70](https://github.com/Jamonek/Robinhood/issues/70) not answer your question?

**Comment by jasonleehodges** [comment]
Not sure I understand what you are saying. The get_account() method (that #70 was referring to) returns json that has a key called "buying power" that shows you your current buying power.

**Comment by jasonleehodges** [comment]
@Njreardo were you able to figure this out?

**Comment by Supanik** [comment]
I believe this is excess_margin
